### ISSUE TITLE
"homeassistant-supervised depends on os-agent", but os-agent:armhf is installed

### ISSUE THREAD

**Issue by jnpwly** [home-assistant/supervised-installer#162]
Kia ora 👋

I have just tried installing a new "supervised" installation, and I am blocked since `homeassistant-supervised` does not recognise my installation of `os-agent:armhf`:

```
jon@OXYGEN:~/Containers/HomeAssistant$ lsb_release -d
Description:    Debian GNU/Linux 10 (buster)
jon@OXYGEN:~/Containers/HomeAssistant$ uname -a
Linux OXYGEN 5.10.63-rockchip64 #21.08.2 SMP PREEMPT Wed Sep 8 10:57:23 UTC 2021 aarch64 GNU/Linux
jon@OXYGEN:~/Containers/HomeAssistant$ sudo aptitude search os-agent
i   os-agent:armhf                                                                       - Home Assistant OS Agent
jon@OXYGEN:~/Containers/HomeAssistant$ sudo dpkg -i homeassistant-supervised.deb
(Reading database ... 40896 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
Leaving 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Leaving 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Leaving 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Leaving 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.0.1) over (1.0.1) ...
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on os-agent.

dpkg: error processing package homeassistant-supervised (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 homeassistant-supervised
jon@OXYGEN:~/Containers/HomeAssistant$```

**Comment by ikifar2012** [comment]
Interestingly, I get this when running `dpkg-deb --info os-agent_1.2.2_linux_armv7.deb`
```bash
root@ha-su-deb:~/os-agent/os-agent_1.2.2_linux_armv7# dpkg-deb --info os-agent_1.2.2_linux_armv7.deb
 new Debian package, version 2.0.
 size 2426724 bytes: control archive=590 bytes.
       1 bytes,     0 lines      conffiles
     254 bytes,    10 lines      control
     200 bytes,     3 lines      md5sums
      91 bytes,     4 lines   *  postinst             #!/bin/bash
      36 bytes,     2 lines   *  postrm               #!/bin/bash
      67 bytes,     3 lines   *  prerm                #!/bin/bash
 Package: os-agent
 Version: 1.2.2
 Section: default
 Priority: extra
 Architecture: armhf
 Maintainer: Home Assistant <hello@home-assistant.io>
 Installed-Size: 5504
 Depends: udisks2
 Homepage: https://www.home-assistant.io
 Description: Home Assistant OS Agent
```

**Comment by ikifar2012** [comment]
the package name is unchanged

**Comment by ikifar2012** [comment]
Another thing I would like to point out is that you are not on Debian Bullseye, could you try updating?

**Comment by jnpwly** [comment]
Many thanks, @ikifar2012.

I see the same output from `dpkg-deb --info os-agent_1.2.2_linux_armv7.deb`. I can only guess that when `dpkg` attempts to install `homeassistant-supervised` it is incorrectly determining that `os-agent` is not installed. Perhaps something (I don't know what...?) needs to parse for `os-agent:armhf`...?

Updating to `bullseye` is a possibilty at some stage, but not just now. 

I think that `buster` should be within the "supported by deprecated" window until 14 December, maybe?

**Comment by jnpwly** [comment]
Oh, one other thing, I see this:
```
jon@OXYGEN:~/Containers/HomeAssistant$ sudo dpkg-deb --info homeassistant-supervised.1.0.1.deb
[sudo] password for jon:
 new Debian package, version 2.0.
 size 4572 bytes: control archive=2416 bytes.
     793 bytes,    14 lines   *  control
    3879 bytes,   129 lines   *  postinst             #!/usr/bin/env
     972 bytes,    28 lines   *  postrm               #!/usr/bin/env
    1384 bytes,    35 lines   *  preinst              #!/usr/bin/env
     280 bytes,     3 lines   *  templates
 Package: homeassistant-supervised
 Section: base
 Version: 1.0.1
 Priority: optional
 Architecture: all
 Depends: curl, bash, docker-ce, dbus, network-manager, apparmor, jq, systemd, os-agent
 Maintainer: Matheson Steplock <https://mathesonsteplock.ca/>
 Homepage: https://www.home-assistant.io/
 Description: Home Assistant Supervised
  This installation method provides the full Home Assistant experience on a regular operating system.
  This means, all components from the Home Assistant method are used, except for the Home Assistant Operating System.
  This system will run the Home Assistant Supervisor. The Supervisor is not just an application, it is a full appliance that manages the whole system.
  It will clean up, repair or reset settings to default if they no longer match expected values.
  ```
  
So, while the `os-agent_1.2.2_linux_armv7.deb` file is reporting `Architecture: armhf`, and `homeassistant-supervised.1.0.1.deb` is reporting `Architecture: all`. I was able to build a `.deb` file that would install by changing the `~/DEBIAN/control` file to have:
```
Depends: curl, bash, docker-ce, dbus, network-manager, apparmor, jq, systemd, os-agent:armhf
```
Worked for me 🤷‍♂️

**Comment by discip** [comment]
@jnpwly
Could you please share your adapted *.deb, or tell me how to build it?

Thanks in advance

**Comment by jnpwly** [comment]
Hi @discip.

To be honest, it was a while ago, and I've since abandoned my attempt to use `homeassistant-supervised`, and instead now have a dedicated Raspberry Pi running Home Assistant OS.

But... You'll need to check out this repo (or fork it, so you have your own copy), and then change [this line](https://github.com/home-assistant/supervised-installer/blob/6adb847f908946b9918a3188229196e33fa2156a/homeassistant-supervised/DEBIAN/control#L6)] so that the `os-agent` is replaced with `os-agent-armhf`. Then, rebuild `homeassisant-supervised` by running:
```
$ dpkg-deb --build homeassisant-supervised
```
(Might ned to `sudo` that...?) And that should create a new `.deb` file, which you can then install (using `dpkg -i homeassistant-supervised`). You might need to suss out which directory to be in when you issue the `dpkg-deb --build homeassisant-supervised` command.

Hope that helps.
   Jon

**Comment by discip** [comment]
@jnpwly 
Thank you for replying, in the meantime I managed to achieve this myself. 😊
Thank you anyway.

**Comment by and7ey** [comment]
Hasn't it been fixed since Nov 2021? I am having the same problem
```
Unpacking homeassistant-supervised (1.2.2) ...
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on os-agent.

dpkg: error processing package homeassistant-supervised (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 homeassistant-supervised
```

os-agent_1.3.0_linux_armv7.deb is installed (Orange Pi One Plus, Armbian 22.08 Jammy)

I have no idea how to change the code and recompile something((

**Comment by and7ey** [comment]
@discip could you please share the file you've got?

**Comment by discip** [comment]
@and7ey
[homeassistant-supervised.deb.txt](https://github.com/home-assistant/supervised-installer/files/9629323/homeassistant-supervised.deb.txt)
Just rename the file by removing the **`.txt`** at the end.

**Comment by MichaelS1955** [comment]
> Oh, one other thing, I see this:
> 
> ```
> jon@OXYGEN:~/Containers/HomeAssistant$ sudo dpkg-deb --info homeassistant-supervised.1.0.1.deb
> [sudo] password for jon:
>  new Debian package, version 2.0.
>  size 4572 bytes: control archive=2416 bytes.
>      793 bytes,    14 lines   *  control
>     3879 bytes,   129 lines   *  postinst             #!/usr/bin/env
>      972 bytes,    28 lines   *  postrm               #!/usr/bin/env
>     1384 bytes,    35 lines   *  preinst              #!/usr/bin/env
>      280 bytes,     3 lines   *  templates
>  Package: homeassistant-supervised
>  Section: base
>  Version: 1.0.1
>  Priority: optional
>  Architecture: all
>  Depends: curl, bash, docker-ce, dbus, network-manager, apparmor, jq, systemd, os-agent
>  Maintainer: Matheson Steplock <https://mathesonsteplock.ca/>
>  Homepage: https://www.home-assistant.io/
>  Description: Home Assistant Supervised
>   This installation method provides the full Home Assistant experience on a regular operating system.
>   This means, all components from the Home Assistant method are used, except for the Home Assistant Operating System.
>   This system will run the Home Assistant Supervisor. The Supervisor is not just an application, it is a full appliance that manages the whole system.
>   It will clean up, repair or reset settings to default if they no longer match expected values.
> ```
> 
> So, while the `os-agent_1.2.2_linux_armv7.deb` file is reporting `Architecture: armhf`, and `homeassistant-supervised.1.0.1.deb` is reporting `Architecture: all`. I was able to build a `.deb` file that would install by changing the `~/DEBIAN/control` file to have:
> 
> ```
> Depends: curl, bash, docker-ce, dbus, network-manager, apparmor, jq, systemd, os-agent:armhf
> ```
> 
> Worked for me 🤷‍♂️

Hi Jon,

I ran into the same error with ver. 1.4.1. But I have no glue how to build the deb-file with "os-agent:armhf". Could you sent me your file?

Michael

**Comment by ikifar2012** [comment]
> > Oh, one other thing, I see this:
> > ```
> > jon@OXYGEN:~/Containers/HomeAssistant$ sudo dpkg-deb --info homeassistant-supervised.1.0.1.deb
> > [sudo] password for jon:
> >  new Debian package, version 2.0.
> >  size 4572 bytes: control archive=2416 bytes.
> >      793 bytes,    14 lines   *  control
> >     3879 bytes,   129 lines   *  postinst             #!/usr/bin/env
> >      972 bytes,    28 lines   *  postrm               #!/usr/bin/env
> >     1384 bytes,    35 lines   *  preinst              #!/usr/bin/env
> >      280 bytes,     3 lines   *  templates
> >  Package: homeassistant-supervised
> >  Section: base
> >  Version: 1.0.1
> >  Priority: optional
> >  Architecture: all
> >  Depends: curl, bash, docker-ce, dbus, network-manager, apparmor, jq, systemd, os-agent
> >  Maintainer: Matheson Steplock <https://mathesonsteplock.ca/>
> >  Homepage: https://www.home-assistant.io/
> >  Description: Home Assistant Supervised
> >   This installation method provides the full Home Assistant experience on a regular operating system.
> >   This means, all components from the Home Assistant method are used, except for the Home Assistant Operating System.
> >   This system will run the Home Assistant Supervisor. The Supervisor is not just an application, it is a full appliance that manages the whole system.
> >   It will clean up, repair or reset settings to default if they no longer match expected values.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, while the `os-agent_1.2.2_linux_armv7.deb` file is reporting `Architecture: armhf`, and `homeassistant-supervised.1.0.1.deb` is reporting `Architecture: all`. I was able to build a `.deb` file that would install by changing the `~/DEBIAN/control` file to have:
> > ```
> > Depends: curl, bash, docker-ce, dbus, network-manager, apparmor, jq, systemd, os-agent:armhf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Worked for me 🤷‍♂️
> 
> Hi Jon,
> 
> I ran into the same error with ver. 1.4.1. But I have no glue how to build the deb-file with "os-agent:armhf". Could you sent me your file?
> 
> Michael
> 
> Hi Jon, I just found here a corrected .deb-file Michael

Can you please provide me with the output of 
`uname -a`
and
`lsb_release -d`
I would also like to ask what device you are running this on?
The original poster of this issue was running an unsupported OS and I have seen others complete the install correctly on devices such as the Raspberry Pi so I thought this had to do with running an unsupported OS, but I am willing to look into this again if your system is supported. I myself do not have anything other than a VM to test on unfortunately so I will need some help recreating this

**Comment by discip** [comment]
**`uname -a`**
```
Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux
```

**`lsb_release -d`**
```
Description: Debian GNU/Linux 11 (bullseye)
```

It is a RaspBerry Pi 4B 8GB

Just let me know what you need and I am happy to assist! 😊

thanks in advance

**Comment by discip** [comment]
**`uname -a`**
```
Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux
```

**`lsb_release -d`**
```
Description: Debian GNU/Linux 11 (bullseye)
```

## It's a RaspBerry Pi 4B 8GB.

Just let me know what you need and I am happy to assist! 😊

thanks in advance

**Comment by ikifar2012** [comment]
@agners do you have any idea what could be causing this issue? The name of the package is the same on all platforms (I even double checked the control files for each version of the os-agent) so I don't see why some are getting this error and others are not I also don't have the hardware to be able to recreate the issue

**Comment by DercioRicardo** [comment]
Have you managed to fix the problem? I got the same issue when i tried to run HA suppervised on my RPI 4 via docker compose.

`root@omv:/home/pi# apt install ./homeassistant-supervised.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'homeassistant-supervised' instead of './homeassistant-supervised.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 homeassistant-supervised : Depends: os-agent but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by MichaelS1955** [comment]
No :-( I gave up for the moment.

**Comment by FrancYescO** [comment]
Same here (on an orangepi4) .. i just forced install and all seems working
`dpkg --force-all -i ./homeassistant-supervised.deb`

**Comment by b1ngfun** [comment]
> Hi @discip.
> 
> To be honest, it was a while ago, and I've since abandoned my attempt to use `homeassistant-supervised`, and instead now have a dedicated Raspberry Pi running Home Assistant OS.
> 
> But... You'll need to check out this repo (or fork it, so you have your own copy), and then change [this line](https://github.com/home-assistant/supervised-installer/blob/6adb847f908946b9918a3188229196e33fa2156a/homeassistant-supervised/DEBIAN/control#L6)] so that the `os-agent` is replaced with `os-agent-armhf`. Then, rebuild `homeassisant-supervised` by running:
> 
> ```
> $ dpkg-deb --build homeassisant-supervised
> ```
> 
> (Might ned to `sudo` that...?) And that should create a new `.deb` file, which you can then install (using `dpkg -i homeassistant-supervised`). You might need to suss out which directory to be in when you issue the `dpkg-deb --build homeassisant-supervised` command.
> 
> Hope that helps. Jon

Hi Jon,

I tried your method to build a deb with 1.7.0 and it works, thanks a lot mate.

**Comment by quinblz** [comment]
Installing the aarch64 version of os-agent fixed the issue for me as well.
