### ISSUE TITLE
Installer broken? something went wrong loading onboaring, try refresh

### ISSUE THREAD

**Issue by Dattel** [home-assistant/supervised-installer#164]
Hi - i tried to install HA-supervised but got stuck on the welcome page "something went wrong loading onboaring, try refresh".

i was able to create a user on the onboarding page, but i can't log in..
I tried 2 different debian VM's - both on bullseye- same result.. It's a fresh installation - without any proxy...

Journal points to:

`Oct 31 21:56:09 debianHa cca9f42f4db9[8091]: 2021-10-31 21:56:09 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from *****.fritz.box (192.168.178.38). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36)
`
any suggestions, how to fix that?

**Comment by ikifar2012** [comment]
Seems like a networking issue, I suggest you ask in the [Discord](https://www.home-assistant.io/join-chat/) I am ikifar#7246
