### ISSUE TITLE
Bug Report: Can't boot on VM created with Vagrant

### ISSUE THREAD

**Issue by richard-scott** [home-assistant/supervised-installer#169]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

inux home-assistant 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### What happened?

I have had problems with installing homeassistant-supervised.deb on a fresh VM.

My VM is a VirtualBox VM setup by Vagrant on an Ubuntu Host the /etc/network/interfaces causes the VM not to be bootable as vagrant needs an extra blank line at the end of it as the original one did/does.

### Machine Type

generic-x86-64

### Installer output

```text
N/a
```

### Relevant log output

```shell
N/a
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
This does not seem like a bug with the installer as I have not changed anything within the `/etc/network/interfaces` file from the original script. 

Also it seems  you are running "Vagrant on an Ubuntu Host" which is not supported by the installer as per the [ADR] (https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) which states only "Debian 11 aka Bullseye (no derivatives)" is supported

However, if you believe this is a small enough change that it won't affect anyone else running a supported installation and you can test to confirm that then no one is stopping you from making a PR
