### ISSUE TITLE
Bug Report: Can't install homeassistant-supervised.deb

### ISSUE THREAD

**Issue by summetdev** [home-assistant/supervised-installer#171]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux debian 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### What happened?

I encourented an issue installing homeassistant-supervised.deb on my Debian machine.
Steps to reproduce:
1. Run `dpkg -i ./homeassistant-supervised.deb` (with homeassistant-supervised.deb in directory)
2. Installer will fail with error log below.

### Machine Type

generic-x86-64

### Installer output

```text
(Reading database ... 90604 files and directories currently installed.)
Preparing to unpack ./homeassistant-supervised.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
Leaving 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Leaving 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Leaving 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Leaving 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.0.2) over (1.0.2) ...
Setting up homeassistant-supervised (1.0.2) ...
[info] Restarting NetworkManager
[info] Restarting docker service
PING version.home-assistant.io (104.26.4.238) 56(84) bytes of data.
64 bytes from 104.26.4.238 (104.26.4.238): icmp_seq=1 ttl=56 time=30.1 ms

--- version.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 30.098/30.098/30.098/0.000 ms
[info] Install supervisor Docker container
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:60704->[::1]:53: read: connection refused
dpkg: error processing package homeassistant-supervised (--install):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 homeassistant-supervised
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
Are you on the latest version of Docker-CE?

**Comment by summetdev** [comment]
> Are you on the latest version of Docker-CE?

Yes, I do:
```
# docker -v
Docker version 20.10.11, build dea9396
```
> `docker run hello-world`

Yes, this command works as expected.

**Comment by ikifar2012** [comment]
it seems to be getting stuck on `docker pull homeassistant/amd64-hassio-supervisor:2021.10.8`

**Comment by ikifar2012** [comment]
does it fail pulling the supervisor?

**Comment by summetdev** [comment]
> does it fail pulling the supervisor?

No, it doesn't. `docker pull` finishes successfully. But the error remains here for some reason.

**Comment by ikifar2012** [comment]
The command I gave you was the exact command it was trying to run. The error it is giving you seems to be a DNS error. I assume you have attempted a system update `sudo apt update && sudo apt dist-upgrade` and a reboot, also ensure you are running as root

**Comment by sr01** [comment]
Hi, same behavior on my side, on a fresh install of Debian 11. 
I solve it by Installing resolve.conf service and set Permanent DNS Nameservers [(here)](https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/)

**Comment by summetdev** [comment]
> Hi, same behavior on my side, on a fresh install of Debian 11. 
> I solve it by Installing resolve.conf service and set Permanent DNS Nameservers [(here)](https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/)

Thanks, @sr01, it helped!
