### ISSUE TITLE
Feature request: instructions for headless install of homeassistant-supervised.deb

### ISSUE THREAD

**Issue by AlejandroRivera** [home-assistant/supervised-installer#173]
### OS Version

Ubuntu 20.04.3 LTS

### System Information

Linux rpi-tank 5.4.0-1046-raspi #50-Ubuntu SMP PREEMPT Thu Oct 28 05:32:10 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

### What happened?

I'm trying to set up an Ansible script to install Home Assistant Supervised and when performing the step following step, my ansible playbook gets stuck:
```
wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
dpkg -i homeassistant-supervised.deb
```
The reason it gets stuck is because the installation process prompts to select for the machine type. How can I specify the correct value via command line? 

Since i've not completed the installation, i also don't know if there are there other prompts that also need to be addressed in a similar way, so pls let me know.

Thanks!

### Machine Type

raspberrypi4-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Kanga-Who** [comment]
> ### OS Version
> 
> Ubuntu 20.04.3 LTS

This is not a Supported OS. You state you have read the ADR in your OP, please read it again.

**Comment by AlejandroRivera** [comment]
Sorry the information provided about OS and System info was taken by mistake from my host controller. The target host is indeed a Debian 11 OS.

**Comment by AlejandroRivera** [comment]
I'm still interested in this feature or at least a suggested workaround. I've been unable to find a way to specify installation options directly with the `dpkg` command.

**Comment by frenck** [comment]
So, headless is already possible, I think the term searched for here is Unattended. The setup procedure is meant to be interactive and unattended isn't our goal.

Additionally, the reported OS isn't supported by us (Ubuntu 20.04.3 LTS).

Closing this feature request for the above reasoning.

**Comment by AlejandroRivera** [comment]
Thanks Frenck, you are right, the correct term should have been "unattended".
Regarding the OS, i explained in my second [comment](https://github.com/home-assistant/supervised-installer/issues/173#issuecomment-981293521) that the OS was indeed Debian and not Ubuntu. 

Finally, I found a way to make this work and perhaps others would benefit from knowing that they can define the machine type without user interaction by executing the following:

```
$ cat << EOF | sudo debconf-set-selections
homeassistant-supervised    ha/machine-type    select    <machine-type>
EOF
```

where `<machine_type>` is replaced with a valid value, such as `raspberrypi4-64`.

I'll leave it at this and you can decide if you want to document this approach or not.

**Comment by ithinkido** [comment]
> Thanks Frenck, you are right, the correct term should have been "unattended". Regarding the OS, i explained in my second [comment](https://github.com/home-assistant/supervised-installer/issues/173#issuecomment-981293521) that the OS was indeed Debian and not Ubuntu.
> 
> Finally, I found a way to make this work and perhaps others would benefit from knowing that they can define the machine type without user interaction by executing the following:
> 
> ```
> $ cat << EOF | sudo debconf-set-selections
> homeassistant-supervised    ha/machine-type    select    <machine-type>
> EOF
> ```
> 
> where `<machine_type>` is replaced with a valid value, such as `raspberrypi4-64`.
> 
> I'll leave it at this and you can decide if you want to document this approach or not.

This info really needs to be put somewhere so people can find it easily

**Comment by frenck** [comment]
> This info really needs to be put somewhere so people can find it easily

This is default Debian configuration handling. Please note, this is an advanced installation method. We assume you know your way around the Debian/Linux system and this should not raise a question or surprise for you. Please consider and take a look in using other installation methods that might be a better fit for you. (Please don't take it personally, it is honest advice).

../Frenck

**Comment by AlejandroRivera** [comment]
Would you be opposed to a PR that adds this information to the readme (or at least some hints of it) for those less versed on the Debian *packaging/configuration system* but comfortable enough with Linux from a sysadmin/devops perspective?

**Comment by ithinkido** [comment]
> > This info really needs to be put somewhere so people can find it easily
> 
> This is default Debian configuration handling. Please note, this is an advanced installation method. We assume you know your way around the Debian/Linux system and this should not raise a question or surprise for you. Please consider and take a look in using other installation methods that might be a better fit for you. (Please don't take it personally, it is honest advice).
> 
> ../Frenck

Thank you  for the advice. I have considered the other install methods and I will continue to use the HA supervised method as it best fit my needs. Thanks to @AlejandroRivera I now have an efficient way of installing the same thing that I would have other wise done anyway, but had to baby sit the install.  Once again, I think that this should be more visible , eg as in the proposed PR to the current readme by Alejandro,

**Comment by frenck** [comment]
> Would you be opposed to a PR that adds this information to the readme

Yes I would, as we don't want to advertise unattended installations.

**Comment by AlejandroRivera** [comment]
I understand and will respect your decision 🙇‍♂️ 
Just to close this thread, I want to say: Thanks for all you've done on this project!
