### ISSUE TITLE
homeassistant-supervised.deb overwrites /etc/network/interfaces

### ISSUE THREAD

**Issue by magicus** [home-assistant/supervised-installer#176]
I installed homeassistant-supervised.deb on my Ubuntu machine. Afterwards, my bridge configuration stopped working. After some debugging, I found out that homeassistant-supervised.deb had overwritten my /etc/network/interfaces, removing my bridge configuration. 

I realize that I do not fully adhere to the ADR spec since I'm using the machine as a bridge as well. Nevertheless, this was highly unexpected, and at least a warning before overwriting files in /etc would have been much appreciated.

**Comment by Kanga-Who** [comment]
Did you read the ADR?

The operating system is dedicated to running Home Assistant Supervised.
...... 
No additional software, outside of the Home Assistant ecosystem, is installed.

**Comment by magicus** [comment]
Yes, as I said, I understand that my system does not fully adhere to the ADR. Nevertheless, I think that I am not the only one who wants to run HA on a machine with other services. There seem to be few reasons to chose this installation method over HassOS if you really have a dedicated machine. So my interpretation here is more like "You're on your own", and I realize that. 

With that said, I just thought it would be courteous of the installer to at least warn before overwriting system files in /etc.

But feel free to close this report if you disagree.

**Comment by Kanga-Who** [comment]
The ADR, which you have read, warns you enough. That's the point of it.

You have chosen to run an OS that is not compatible, plus services that are not compatible, yet wonder why you have a problem.

If you want the Supervisor, run something like Proxmox and install a HA OS VM and then you can spin up another VM to run whatever you like.
