### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by capelo0** [home-assistant/supervised-installer#178]
During the last step, I get this error when trying to perform the installation:

```
root@docker ~# dpkg -i homeassistant-supervised.deb
(Reading database ... 28729 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[info] Fix kernel dmesg restriction
/var/lib/dpkg/tmp.ci/preinst: line 21: /proc/sys/kernel/dmesg_restrict: Read-only file system
dpkg: error processing archive homeassistant-supervised.deb (--install):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Undo divert on abort-install
No diversion 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised', none removed.
Errors were encountered while processing:
 homeassistant-supervised.deb
```

I'm using PVE 7.1-4, TurnKey Linux Docker in LCX container with Docker v.20.10.11 and Portainer.io 2.11.0. 

Don't know why I'm not able to install. Could you please help me understand what I am doing wrong, or clarify if it's a bug?
Thank you.

**Comment by ikifar2012** [comment]
Only Debian is supported no derivatives, both TurnKey Linux and LCX containers are not supported, I suggest you read the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) for more info

**Comment by capelo0** [comment]
Thank you @ikifar2012 for the quick reply. I understand that it may be hard to make things compatible with all the possibilities. I had read that documentation, and tried to install as:
"The Home Assistant team will not prevent you from running Home Assistant using an unofficial method. However, we cannot help with issues that you encounter. We are open for contributions that improve compatibility with a community-supported method as long as they do not impact officially supported methods, add a significant amount of code exceptions or future maintenance burden on the Home Assistant development team."

This could be an error that could be easily solve and just wanted to know if someone more knowledgeable than me, could help. 
Thank you for understanding.

**Comment by ikifar2012** [comment]
It is trying to write zero to a file with this command `echo 0 > /proc/sys/kernel/dmesg_restrict` but it can't because that area of the filesystem seems to be read only

You could try repackaging the Debian package for yourself without the two commands in that area of the preinst but I don't know if that will work and could break in the future if it does. Personally I would recommend you create a Debian bullseye VM.
