### ISSUE TITLE
Installer using raspberrypi3-64-homeassistant image for a Raspberry Pi3 armv7l (32 bit)

### ISSUE THREAD

**Issue by realknotworking** [home-assistant/supervised-installer#182]
### OS Version

Raspbian GNU/Linux 11 (bullseye)

### System Information

Linux pi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux

### What happened?

I've run through the instructions on the supervised-installer page several times (https://github.com/home-assistant/supervised-installer), each time it has downloaded the raspberrypi3-64 image for my 32 bit Pi3 (ghcr.io/home-assistant/raspberrypi3-64-homeassistant:landingpage). 
All the other containers start and run except for the 64 bit core it keeps exiting with the error:
`[8990]: standard_init_linux.go:228: exec user process caused: exec format error`

Searching the internet on the error confirmed it's a platform/architecture error, trying to run the 64 bit image on 32 bit machine. I removed the particular container/image and downloaded what I thought must be the correct image for the supervised install,
**ghcr.io/home-assistant/armv7-homeassistant:latest**
and all the containers are now up and I can access the frontend.

```
7f5dd60467fc   ghcr.io/home-assistant/armv7-hassio-multicast:2021.04.0    "/init"                  6 minutes ago    Up 6 minutes                                           hassio_multicast
ce6b9608a7d6   ghcr.io/home-assistant/armv7-hassio-audio:2021.07.0        "/init"                  6 minutes ago    Up 6 minutes                                           hassio_audio
f436e9cefe07   ghcr.io/home-assistant/armv7-hassio-dns:2021.06.0          "/init"                  6 minutes ago    Up 6 minutes                                           hassio_dns
eae20a01cade   ghcr.io/home-assistant/armv7-hassio-cli:2021.09.0          "/init /bin/bash -c …"   6 minutes ago    Up 6 minutes                                           hassio_cli
6f3ad0e7ae63   ghcr.io/home-assistant/armv7-homeassistant:latest   "/init"                  43 minutes ago   Up 2 minutes                                           homeassistant
c3af43269c3a   ghcr.io/home-assistant/armv7-hassio-observer:2021.10.0     "/init"                  3 hours ago      Up 7 minutes   0.0.0.0:4357->80/tcp, :::4357->80/tcp   hassio_observer
ac73de4476b3   homeassistant/armv7-hassio-supervisor                      "/init"                  3 hours ago      Up 7 minutes                                           hassio_supervisor
```
The problem is there are no addons option, when I try to access http://192.168.1.166:8123/_my_redirect/supervisor I get a message telling me I need either the HA OS or Supervised Installation method. 

Am I missing something? I'm following all the steps correctly. Is it that I'm on Raspian instead of Debian??

### Machine Type

raspberrypi3

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
> Am I missing something? I'm following all the steps correctly. Is it that I'm on Raspian instead of Debian??
You are correct, Raspbian is not supported, you must be using one of the official Raspberry Pi Debian images 

You also should have selected raspberrypi3 instead of raspberrypi3-64 during first install, to reset that you would have to run `echo PURGE | debconf-communicate homeassistant-supervised` before restarting the installer

**Comment by realknotworking** [comment]
> > Am I missing something? I'm following all the steps correctly. Is it that I'm on Raspian instead of Debian??
> 
> You are correct, Raspbian is not supported, you must be using one of the official Raspberry Pi Debian images
> 
> You also should have selected raspberrypi3 instead of raspberrypi3-64 during first install, to reset that you would have to run `echo PURGE | debconf-communicate homeassistant-supervised` before restarting the installer

Thanks! I figured that would probably be the situation, so I've been putting a Debian onto another Pi. I only use the Raspian Pi for Pihole, should be easy to move it over.

Thanks also for the PURGE tip. I never would have figured that one out.

**Comment by ikifar2012** [comment]
> Thanks also for the PURGE tip. I never would have figured that one out.

I am working on adding this into the uninstall script of this package, just trying to figure out the easiest way to cleanup all the containers
