### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by geldelo** [home-assistant/supervised-installer#184]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux HA 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### What happened?

Please help, error during installation:

version.home-assistant.io: Unknown name or service
…
Error response from daemon: Get “https://registry-1.docker.io/v2/ 1”: certificate is valid for jenkins.bison.services, *.bison.services, not registry-1.docker.io

I reviewed everything in Google, nothing helps.

P.S. DNS set to 8.8.8.8. The network is stable, I do not use proxy, the server IP address is static.

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
Feel free to @ me (ikifar#7246) on the [Home Assistant Discord](https://www.home-assistant.io/join-chat/) so we can help you get to the bottom of this issue.
