### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by cociweb** [home-assistant/supervised-installer#185]
### OS Version

Ubuntu 20.04.3 LTS

### System Information

Linux ha-su 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What happened?

The installer require (depend) the os-agent. Since OS-Agent is not compatible with the latest Ubuntu release (makes an unhealthy installation), it needs to be removed after the installation of homeassistant-installer.deb.
If you try to remove the OS-Agent without the dependent package it breaks the apt package handler: not able to upgrade without the re-installation of os-agent or the uninstall of homeassistant-supervised.

Also relevant tickets:
https://github.com/home-assistant/os-agent/issues/63
https://github.com/home-assistant/os-agent/issues/57

### Machine Type

qemux86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frenck** [comment]
> Ubuntu 20.04.3 LTS


Is not a supported system.
