### ISSUE TITLE
Bug Report: Missing ability to customize data share, prefix and syscoonfig

### ISSUE THREAD

**Issue by denysdovhan** [home-assistant/supervised-installer#187]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux smart-home 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux

### What happened?

I used to install HA Supervised into a custom directory `$HOME/smart-home/hassio` in order to keep HA Supervised besides other other of my home services. It was easy to do with flags for `installer.sh` script that used to [accept these flags](https://github.com/home-assistant/supervised-installer/tree/e2a66e35d34866d95597937b5cb6852c9d5aea6b#command-line-arguments):

| argument           | default                                                                                                                                                                             | description                                            |
|--------------------|----------------------|--------------------------------------------------------|
| -m \| --machine    |                      | On a special platform they need set a machine type use |
| -d \| --data-share | $PREFIX/share/hassio | data folder for hass.io installation                   |
| -p \| --prefix     | /usr                 | Binary prefix for hass.io installation                 |
| -s \| --sysconfdir | /etc                 | Configuration directory for hass.io installation       |

Unfortunately, after migration to `deb` package it's no longer possible to change these params.

I discovered that `postinst` [reads `DATA_SHARE` from the environment](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/postinst#L83) and tried passing env variables like this, but it doesn't change anything:

```
DATA_SHARE=$HOME/smart-home/hassio dpkg -i homeassistant-supervised.deb
```

P.S: I'm opening this issue, because @ikifar2012 [asked me to do so](https://discord.com/channels/330944238910963714/330944238910963714/935265278063943810) in Discord.

### Machine Type

raspberrypi4-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by PW999** [comment]
I'm facing the same issue and the installer does support some environment variables wich provide these functionality, but so far it's not working for me.

E.g. https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/postinst#L89

**Comment by PW999** [comment]
After re-installing everything I can confirm that at least this works
`DATA_SHARE=/srv/homeassistant dpkg --force-confdef --force-confold -i /srv/setup/homeassistant-supervised.deb`

However, you still have to create the folders yourself.

**Comment by ikifar2012** [comment]
> After re-installing everything I can confirm that at least this works `DATA_SHARE=/srv/homeassistant dpkg --force-confdef --force-confold -i /srv/setup/homeassistant-supervised.deb`
> 
> However, you still have to create the folders yourself.

I think this might be the way to go, as I am not sure I really want to pop up additional questions for every user as most would just use the defaults and might get confused

**Comment by sermayoral** [comment]
> After re-installing everything I can confirm that at least this works `DATA_SHARE=/srv/homeassistant dpkg --force-confdef --force-confold -i /srv/setup/homeassistant-supervised.deb`
> 
> However, you still have to create the folders yourself.

Wow, this is very important. It should appear in the README file on this project.

Thanks!!

**Comment by facutopa** [comment]
Hey guys, is possible this don't work anymore?
DATA_SHARE=/srv/homeassistant dpkg --force-confdef --force-confold -i homeassistant-supervised.deb
I'm using the data_share tag but in the installation ignore the directory assigned.
