### ISSUE TITLE
Bug Report: generic-x86_64 machine type is generated instead of raspberrypi4-64

### ISSUE THREAD

**Issue by harsh2029** [home-assistant/supervised-installer#191]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux rpi-hass 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux

### What happened?

dpkg generates wrong configuration for "machine" in `/etc/hassio.json` below is the output of `cat /etc/hassio.json`
```
{
    "supervisor": "homeassistant/aarch64-hassio-supervisor",
    "machine": "generic-x86-64",
    "data": "/usr/share/hassio"
}

```
The expected "machine" should be `raspberrypi4-64`. The installer didn't even asked to select the machine type.
Since I am running this on Raspberry Pi OS and due to this configuration, incorrect homeassistant docker image is pulled (x86_64) which obviously won't run on aarch64 (rapberrypi4-64) machine.

### Machine Type

raspberrypi4-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
I am publishing a release today to hopefully fix this

**Comment by ikifar2012** [comment]
https://github.com/home-assistant/supervised-installer/releases/tag/1.1.0
