### ISSUE TITLE
Bug Report: homeassistant-supervised install error

### ISSUE THREAD

**Issue by ngnxuanhoa** [home-assistant/supervised-installer#195]
### OS Version

Debian bullseye

### System Information

os-agent_1.2.2_linux_armv7.deb

### What happened?

i encounted while settup home-assistant suppervisor, pls help me
--- version.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 51.228/51.228/51.228/0.000 ms
Device "eth0
eth0
wlan0" does not exist.
[info] Install supervisor Docker container
invalid reference format
dpkg: error processing package homeassistant-supervised (--configure):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 homeassistant-supervised
E: Sub-process /usr/bin/dpkg returned an error code (1)

Check: journalctl -f
Mar 15 20:28:10 raspberrypi hassio-supervisor[9333]: 22-03-15 20:28:10 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 15 20:28:10 raspberrypi 9ab8bacc70aa[8467]: 22-03-15 20:28:10 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 15 20:28:10 raspberrypi 9ab8bacc70aa[8467]: 22-03-15 20:28:10 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
Mar 15 20:28:10 raspberrypi hassio-supervisor[9333]: 22-03-15 20:28:10 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant

### Machine Type

raspberrypi4

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ngnxuanhoa** [comment]
> Can you attempt reinstalling with the debian package here? https://github.com/home-assistant/supervised-installer/suites/5668508376/artifacts/185927868

i issue :wget https://github.com/home-assistant/supervised-installer/suites/5668508376/artifacts/185927868
but file is not available

**Comment by ikifar2012** [comment]
@ngnxuanhoa that link is a link to a github actions artifact, when clicked it will download a zip file, inside that zip is the deb file, it appears you cannot wget it

**Comment by ngnxuanhoa** [comment]
> @ngnxuanhoa that link is a link to a github actions artifact, when clicked it will download a zip file, inside that zip is the deb file, it appears you cannot wget it
Dear my friend
the error still occurs
info] Install supervisor Docker container
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
[info] Within a few minutes you will be able to reach Home Assistant at:
[info] http://homeassistant.local:8123 or using the IP address of your
[info] machine: http://:8123
root@raspberrypi:~# journalctl -f
-- Journal begins at Fri 2022-01-28 08:30:20 +07. --
Mar 16 18:07:25 raspberrypi dhcpcd[430]: wlan0: adding default route via 192.168.0.1
Mar 16 18:07:25 raspberrypi systemd[1]: Stopping Network Time Synchronization...
Mar 16 18:07:25 raspberrypi systemd[1]: systemd-timesyncd.service: Succeeded.
Mar 16 18:07:25 raspberrypi systemd[1]: Stopped Network Time Synchronization.
Mar 16 18:07:25 raspberrypi systemd[1]: Starting Network Time Synchronization...
Mar 16 18:07:26 raspberrypi systemd[1]: Started Network Time Synchronization.
Mar 16 18:07:26 raspberrypi systemd-timesyncd[14623]: Initial synchronization to time server 203.113.174.44:123 (0.debian.pool.ntp.org).
Mar 16 18:07:34 raspberrypi dhcpcd[430]: wlan0: no IPv6 Routers available
Mar 16 18:07:37 raspberrypi systemd[1]: systemd-hostnamed.service: Succeeded.
Mar 16 18:07:37 raspberrypi systemd[1]: systemd-timedated.service: Succeeded.
Mar 16 18:09:07 raspberrypi a49a5940e879[10898]: 2022-03-16 18:09:07 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.30.32.2 (172.30.32.2). (HomeAssistantSupervisor/2022.03.4 aiohttp/3.8.1 Python/3.9)
Mar 16 18:09:07 raspberrypi 9ab8bacc70aa[10898]: 22-03-16 18:09:07 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 16 18:09:07 raspberrypi hassio-supervisor[11900]: 22-03-16 18:09:07 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 16 18:09:07 raspberrypi hassio-supervisor[11900]: 22-03-16 18:09:07 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
Mar 16 18:09:07 raspberrypi 9ab8bacc70aa[10898]: 22-03-16 18:09:07 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
Mar 16 18:11:07 raspberrypi a49a5940e879[10898]: 2022-03-16 18:11:07 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.30.32.2 (172.30.32.2). (HomeAssistantSupervisor/2022.03.4 aiohttp/3.8.1 Python/3.9)
Mar 16 18:11:07 raspberrypi 9ab8bacc70aa[10898]: 22-03-16 18:11:07 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 16 18:11:07 raspberrypi hassio-supervisor[11900]: 22-03-16 18:11:07 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 16 18:11:07 raspberrypi hassio-supervisor[11900]: 22-03-16 18:11:07 ERROR (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant API!
Mar 16 18:11:07 raspberrypi 9ab8bacc70aa[10898]: 22-03-16 18:11:07 ERROR (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant API!
Mar 16 18:11:07 raspberrypi 9ab8bacc70aa[10898]: 22-03-16 18:11:07 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
Mar 16 18:11:07 raspberrypi hassio-supervisor[11900]: 22-03-16 18:11:07 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
Mar 16 18:11:07 raspberrypi a49a5940e879[10898]: [cont-finish.d] executing container finish scripts...
Mar 16 18:11:07 raspberrypi a49a5940e879[10898]: [cont-finish.d] done.
Mar 16 18:11:07 raspberrypi a49a5940e879[10898]: [s6-finish] waiting for services.
Mar 16 18:11:12 raspberrypi a49a5940e879[10898]: [finish] process exit code 0
Mar 16 18:11:12 raspberrypi a49a5940e879[10898]: s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening

**Comment by ikifar2012** [comment]
It appears this time the actual install script has succeeded but something else strange is going on, your home assistant access token appears to be invalid 

have you tried `ha su repair`

also can I get the exact output of `uname -a` and `lsb_release -d`

**Comment by ngnxuanhoa** [comment]
> lsb_release -d
This show below:
root@raspberrypi:~# ha su repair
Command completed successfully.
root@raspberrypi:~# uname -a
Linux raspberrypi 5.10.103-v7l+ #1530 SMP Tue Mar 8 13:05:01 GMT 2022 armv7l GNU/Linux
root@raspberrypi:~# lsb_release -d
Description:	Raspbian GNU/Linux 11 (bullseye)
root@raspberrypi:~# 
The error sitll appear:
Mar 17 06:27:01 raspberrypi sudo[5161]:       pi : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/bash
Mar 17 06:27:01 raspberrypi sudo[5161]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Mar 17 06:27:09 raspberrypi 9ab8bacc70aa[721]: 22-03-17 06:27:09 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 17 06:27:09 raspberrypi a49a5940e879[721]: 2022-03-17 06:27:08 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.30.32.2 (172.30.32.2). (HomeAssistantSupervisor/2022.03.4 aiohttp/3.8.1 Python/3.9)
Mar 17 06:27:09 raspberrypi hassio-supervisor[1958]: 22-03-17 06:27:09 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
Mar 17 06:27:09 raspberrypi hassio-supervisor[1958]: 22-03-17 06:27:09 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
Mar 17 06:27:09 raspberrypi 9ab8bacc70aa[721]: 22-03-17 06:27:09 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant

**Comment by ikifar2012** [comment]
Raspbian bullseye is not supported, as per the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) only Debian is supported therefore I will be closing this issue

Please consider migrating to either the official [Debian Image for Raspberry Pi](https://raspi.debian.net/tested-images/) or [Home Assistant OS](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system)
