### ISSUE TITLE
Bug Report: fresh minimal Debian 11 install fails because package os-agent is not installed

### ISSUE THREAD

**Issue by redgryphon** [home-assistant/supervised-installer#203]
### OS Version

Description:	Debian GNU/Linux 11 (bullseye)

### System Information

Linux test-homeassistant 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux

### What happened?

Install a fresh Debian 11 using the graphical install mode and remove all the checkboxes for the package selection.
Install all the dependencies required from the README file.
Download the 1.1.0 homeassistant-supervised deb file.

Notice the error when the installation fails.

### Machine Type

generic-x86-64

### Installer output

```text
Selecting previously unselected package homeassistant-supervised.
(Reading database ... 34918 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
[info] Fix kernel dmesg restriction
Adding 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Adding 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Adding 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Adding 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.1.0) ...
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on os-agent; however:
  Package os-agent is not installed.

dpkg: error processing package homeassistant-supervised (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 homeassistant-supervised
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frenck** [comment]
You can find the OS Agent here:

<https://github.com/home-assistant/os-agent>
