### ISSUE TITLE
Bug Report: Armbian install fails

### ISSUE THREAD

**Issue by mrallengod** [home-assistant/supervised-installer#205]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux aml-s812 5.10.68-aml-s812 #20.12 SMP Thu Sep 23 18:34:14 CST 2021 armv7l GNU/Linux

### What happened?

Install supervisor get an errors on an armbian os.

### Machine Type

qemuarm-64

### Installer output

```text
[info] Install supervisor Docker container
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
grep: /etc/default/grub: No such file or directory
[info] Switching to cgroup v1
cp: cannot stat '/etc/default/grub': No such file or directory
dpkg: error processing package homeassistant-supervised (--configure):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
Setting up grub2-splashimages (1.0.1+nmu2) ...
Errors were encountered while processing:
 homeassistant-supervised
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frenck** [comment]
Armbian is not a supported operating system.
