### ISSUE TITLE
Bug Report: /etc/default/grub: No such file or directory

### ISSUE THREAD

**Issue by zakhenry** [home-assistant/supervised-installer#207]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux rpi2-20220121 5.10.0-11-armmp #1 SMP Debian 5.10.92-1 (2022-01-18) armv7l GNU/Linux

### What happened?

Running install of the package gets the following error (same as #205):

```
[info] Install supervisor Docker container
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
grep: /etc/default/grub: No such file or directory
```

Downgrading to 1.1.0 fixes the issue so I'm going with that in the interim.

### Machine Type

raspberrypi2

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Doktor-X** [comment]
I have also used 1.1.0 to install on armbian

**Comment by AdamN1** [comment]
> I have also used 1.1.0 to install on armbian

armbian dosn't use grub thats way you have error.
You can pass this error using this command
```
echo 'GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=false quite"' > /etc/default/grub
```

**Comment by AdamN1** [comment]
Long term solution is checking that system is using grub or uboot and skip check for system using uboot

**Comment by Steve973** [comment]
For systems without grub, you need to do the following:

1. Add systemd.unified_cgroup_hierarchy=false to /etc/default/grub.
2. Add systemd.unified_cgroup_hierarchy=false to the end of /boot/cmdline.txt.
3. Reboot.
4. Install HA supervised.

It would be *very* nice if the installation script would do this for users after checking if the necessary files exist and/or contain the required information.
