### ISSUE TITLE
Installation fails when grub is not installed

### ISSUE THREAD

**Issue by metamono** [home-assistant/supervised-installer#208]
The post-install script keeps being triggered after every update when `/etc/default/grub` is not available 

https://github.com/home-assistant/supervised-installer/blob/da3b7ae7ced983daf5e2264cd97f291f938eedad/homeassistant-supervised/DEBIAN/postinst#L141

This causes the install to be not completed.

Experienced on a RaspianOS

**Comment by ikifar2012** [comment]
Raspbian/Raspberry Pi OS is not supported, as per the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) only Debian is supported, therefore I will be closing this issue

Please consider migrating to either the official [Debian Image for Raspberry Pi](https://raspi.debian.net/tested-images/) or [Home Assistant OS](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system)

If you need any help switching over to a supported OS, feel free to reach out on [Discord](https://www.home-assistant.io/join-chat/) or the [Home Assistant Community Forums](https://community.home-assistant.io/)

**Comment by metamono** [comment]
For everyone who doesnt want to install a separate disk image for every server on the raspi use as a quickfix to uncomment the last `IF...FI` section for GRUB in `/var/lib/dpkg/info/homeassistant-supervised.postinst` like this to install the supervised version on raspianOS:

```bash
# install all required dependencies before installing hassio supervised
sudo wget https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_aarch64.deb
sudo dpkg -i os-agent_1.2.2_linux_aarch64.deb 
sudo wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
sudo dpkg -i homeassistant-supervised.deb
sudo nano /var/lib/dpkg/info/homeassistant-supervised.postinst # comment out last section for grub and install again
sudo dpkg -i homeassistant-supervised.deb
```
Not guarantied to work.. please check for your own situation

**Comment by pacmac** [comment]
## Setup dummy support for grub
touch /etc/default/grub
touch /usr/sbin/update-grub
chmod +x  /usr/sbin/update-grub
