### ISSUE TITLE
Bug Report: cmdline.txt not found 

### ISSUE THREAD

**Issue by Patrick010** [home-assistant/supervised-installer#221]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux 5.10.0-15-arm64 #1 SMP Debian 5.10.120-1 (2022-06-09) aarch64 GNU/Linux

### What happened?

I followed the installation guide on https://community.home-assistant.io/t/installing-home-assistant-supervised-on-a-raspberry-pi-with-debian-11/247116
In step 3.1 homeassistant-supervised.deb is downloaded and installed. While installing a warning is produced:

[warn] Could not find /etc/default/grub or /boot/cmdline.txt failed to switch to cgroup v1

In my case cmdline.txt is found in /boot/firmware/
Apparently systemd.unified_cgroup_hierarchy=false is added to the commandline, which I did manually.
I dont know if this is the only thing that failed, but the script continues without any further warnings or errors.

### Machine Type

raspberrypi4-64

### Installer output

```text
root@xxxx:~# dpkg -i homeassistant-supervised.deb
(Reading database ... 28808 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
Leaving 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Leaving 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Leaving 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Leaving 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.2.1) over (1.2.1) ...
Setting up homeassistant-supervised (1.2.1) ...
[info] Restarting NetworkManager
[info] Restarting docker service
PING version.home-assistant.io (104.26.4.238) 56(84) bytes of data.
64 bytes from 104.26.4.238 (104.26.4.238): icmp_seq=1 ttl=59 time=5.07 ms

--- version.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 5.066/5.066/5.066/0.000 ms
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
[warn] Could not find /etc/default/grub or /boot/cmdline.txt failed to switch to cgroup v1
[info] Within a few minutes you will be able to reach Home Assistant at:
[info] http://homeassistant.local:8123 or using the IP address of your
[info] machine: http://192.168.xx.xx:8123
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by neuronflow** [comment]
I am facing the same issue, however I don't have a file here:
` /boot/firmware/`
