### ISSUE TITLE
Can't install ghcr.io/home-assistant/aarch64-hassio-cli:2022.06.0: 500 Server Error 

### ISSUE THREAD

**Issue by evlo** [home-assistant/supervised-installer#223]
### OS Version

ubuntu 22.04

### System Information

Linux hasupervised 5.15.0-1011-oracle #15-Ubuntu SMP Fri Jun 10 12:21:49 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### What happened?

I'm getting 
`Jul 07 23:31:31 hasupervised 3d0bdb059965[999]: 22-07-08 01:31:31 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-cli:2022.06.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.0&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-cli&platform=linux%2Farm64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")`
in `journalctl -f` and home assistant does not install.

_Temporary failure in name resolution?_

I would like to use the supervised mode much more then jsut docker install.

This is ampere arm64 machine, so not exactly supported :/ 

[I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation]

[Ubuntu is obviously debian 11 derivate, also not supported]

### Machine Type

qemuarm-64

### Relevant log output

```shell
Jul 07 23:31:31 hasupervised 3d0bdb059965[999]: 22-07-08 01:31:31 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-cli:2022.06.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.0&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-cli&platform=linux%2Farm64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by evlo** [comment]
```
ping www.google.com
ping: www.google.com: Temporary failure in name resolution
```
guess more is wrong here

**Comment by HeAuDa** [comment]
This happened to me when I had already had docker installed before installing supervisor. All I had to do was reboot and it fixed it.
