### ISSUE TITLE
Bug Report: No network connection

### ISSUE THREAD

**Issue by wes1993** [home-assistant/supervised-installer#226]
### OS Version

Debian/GNU Linux 11

### System Information

Linux Server 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux

### What happened?

After installing homeassistant network won't work anymore.
No LAN connection.
nmcli see 1 connection but not connect
if i do after reboot:
nmcli dev connect enp1s0f1
the connection work but if i reboot the machine again the connection won't work again and i need to ussie the command again

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
is this on the latest version of the installer? it should be fixed. If not let me know and see if the workaround in #217 works for you

**Comment by wes1993** [comment]
Is the latest version, downloaded from the link in the manual.
How can i enable the autoconnect with nmtui?

**Comment by wes1993** [comment]
A little Update:
I have uninstalled and installed again debian 11.4 just the time to install homeassistant and update here :-D

**Comment by wes1993** [comment]
I have another question in the meantime what is the difference between x84_64 and amd64 for the os-agent?

**Comment by wes1993** [comment]
I can confirm that after reinstalling everything and without restore the backup i have the same issue...
no connection

**Comment by wes1993** [comment]
I can confirm that with nmtui and autoconnection works.

**Comment by habuild** [comment]
Nmtui manual worked for me also

**Comment by ikifar2012** [comment]
@wes1993 if you can recreate this issue can you most the content of the file in `/etc/NetworkManager/system-connections`

**Comment by miguelsg29** [comment]
I have a similar problem.

Installing supervised Home Assistant on an Odroid M1 (Debian 11). I select in the installation odroid-n2. Once the installation is done, the home assistant dockers do not have internet and I cannot install HACS.

Note: If I install other dockers if they have internet. It looks like a home assistant bug.

I have tried many options without success.

Thank you very much for your help.

**Comment by SpanishST** [comment]
Got the same problem with raspberry pi 4 and fresh raspberry pi os 64bit, no network after running 
`dpkg -i homeassistant-supervised.deb`

"ip route" is showing a strange metric for eth0 which was 100 at reboot and 20100 after.
`pi@hapi:~ $ ip route
0.0.0.0/1 via 10.8.0.1 dev tun0 
default via 192.168.1.1 dev eth0 proto static metric 20100 
10.8.0.0/24 dev tun0 proto kernel scope link src 10.8.0.3 
128.0.0.0/1 via 10.8.0.1 dev tun0 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.30.32.0/23 dev hassio proto kernel scope link src 172.30.32.1 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.101 metric 100 
`

**Comment by ikifar2012** [comment]
> Got the same problem with raspberry pi 4 and fresh raspberry pi os 64bit, no network after running `dpkg -i homeassistant-supervised.deb`
> 
> "ip route" is showing a strange metric for eth0 which was 100 at reboot and 20100 after. `pi@hapi:~ $ ip route 0.0.0.0/1 via 10.8.0.1 dev tun0 default via 192.168.1.1 dev eth0 proto static metric 20100 10.8.0.0/24 dev tun0 proto kernel scope link src 10.8.0.3 128.0.0.0/1 via 10.8.0.1 dev tun0 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 172.30.32.0/23 dev hassio proto kernel scope link src 172.30.32.1 192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.101 metric 100 `

Raspberry Pi OS is not supported
