### ISSUE TITLE
Unable to update Core and AddOns

### ISSUE THREAD

**Issue by ArtBIT** [home-assistant/supervised-installer#230]
ha info
```
arch: aarch64
channel: stable
docker: 20.10.14
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- os_agent
- haos
- resolved
hassos: "8.5"
homeassistant: 2022.6.4
hostname: homeassistant
logging: info
machine: raspberrypi4-64
operating_system: Home Assistant OS 8.5
state: running
supervisor: 2022.08.3
supported: true
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe
```
When trying to update Home Assistant Core (or any of the AddOns for that matter) I get the following error:
```
Failed to call service update/install. Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
```

When I run `ha net info` I get:
```
$ ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: false
interfaces:
- connected: true
  enabled: true
  interface: eth0
  ipv4:
    address:
    - 192.168.0.101/24
    gateway: 192.168.0.1
    method: static
    nameservers:
    - 192.168.0.1
  ipv6:
    address:
    - fe80::c070:8cf4:b8d9:ef3a/64
    gateway: null
    method: auto
    nameservers:
    - fe80::1
  primary: true
  type: ethernet
  vlan: null
  wifi: null
- connected: false
  enabled: false
  interface: wlan0
  ipv4:
    address: []
    gateway: null
    method: disabled
    nameservers: []
  ipv6:
    address: []
    gateway: null
    method: disabled
    nameservers: []
  primary: false
  type: wireless
  vlan: null
  wifi: null
supervisor_internet: true
```

Which shows that the host does not have access to the internet, but it does.
When I curl the http url I get:
```
$ curl http://checkonline.home-assistant.io/online.txt
curl: (56) Recv failure: Connection reset by peer
```

While the `https` one works:
```
$ curl https://checkonline.home-assistant.io/online.txt
NetworkManager is online
```

It seems that the `http` url should be updated to `https` in:

https://github.com/home-assistant/supervised-installer/blob/2f62e65aab05fba7dbbf70d6c91a02f98067631f/homeassistant-supervised/etc/NetworkManager/NetworkManager.conf#L18

Like in:

https://github.com/home-assistant/supervisor/blob/3f882364957ced1bbf1eecee7e6d339afc0637f8/supervisor/supervisor.py#L251

**Comment by ikifar2012** [comment]
I believe you have another networking related issue as I have kept the NetworkManager config in sync with what HAOS is using 
https://github.com/home-assistant/operating-system/blob/e64e97cedffa40eb66e3a77620b62ef2baa93903/buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf#L18


```bash
$ curl http://checkonline.home-assistant.io/online.txt
NetworkManager is online
```

**Comment by ArtBIT** [comment]
It started working the next day. But at the time, it was down.
It was probably a CloudFlare hickup.

**Comment by ikifar2012** [comment]
Awesome, I will close the issue.
Feel free to check out the [Home Assistant Discord](https://www.home-assistant.io/join-chat/) or [Community Forums](https://community.home-assistant.io/)
