### ISSUE TITLE
Dependency issue - systemd-journal-remote

### ISSUE THREAD

**Issue by mtw20** [home-assistant/supervised-installer#241]
Errors when using `dpkg -i homeassistant-supervised.deb`

Machine type: raspberrypi4
OS: Raspbian GNU/Linux 11 (bullseye)
SysInfo: Linux pi 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux

When executing `dpkg -i homeassistant-supervised.deb`, it ends up with:
```
Unpacking homeassistant-supervised (1.3.0) over (1.3.0) ...
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on systemd-journal-remote; however:
  Package systemd-journal-remote is not installed.

dpkg: error processing package homeassistant-supervised (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 homeassistant-supervised
```

Then i tried `sudo apt-get install systemd-journal-remote` and got:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 systemd-journal-remote : Depends: libmicrohttpd12 (>= 0.9.50) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Then i tried `sudo apt-get install libmicrohttpd12` and got:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
homeassistant-supervised : Depends: systemd-journal-remote but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Could someone advise what to do?

**Comment by maciejpawlak** [comment]
If someone gets here looking for answer - apt-get install libmicrohttpd12 systemd-journal-remote

**Comment by niqu1982** [comment]
@maciejpawlak  I have issue with systemd-journal-remote[5252]: Failed to read key from file '/etc/ssl/private/journal-remote.pem': Permission denied     but i don't want to install ssl any help ?

**Comment by bheinek** [comment]
> If someone gets here looking for answer - apt-get install libmicrohttpd12 systemd-journal-remote

Doesnt work 
`libmicrohttpd12 is already the newest version (0.9.72-2).
systemd-journal-remote is already the newest version (247.3-7+deb11u1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 homeassistant-supervised : Depends: os-agent but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).`
