### ISSUE TITLE
Bug Report: Unsupported system - Network Manager issues

### ISSUE THREAD

**Issue by mokkin** [home-assistant/supervised-installer#256]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux raspberrypi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux

### What happened?

Directly after installing or reinstalling there is no error or warning, but after the first reboot the warning appears.

### Machine Type

raspberrypi4-64

### Installer output

```text
sudo dpkg -i homeassistant-supervised.deb 
(Lese Datenbank ... 43070 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von homeassistant-supervised.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
»Umleitung von /etc/NetworkManager/NetworkManager.conf zu /etc/NetworkManager/NetworkManager.conf.real durch homeassistant-supervised« wird beibehalten
»Umleitung von /etc/NetworkManager/system-connections/default zu /etc/NetworkManager/system-connections/default.real durch homeassistant-supervised« wird beibehalten
»Umleitung von /etc/docker/daemon.json zu /etc/docker/daemon.json.real durch homeassistant-supervised« wird beibehalten
»Umleitung von /etc/network/interfaces zu /etc/network/interfaces.real durch homeassistant-supervised« wird beibehalten
Entpacken von homeassistant-supervised (1.3.1) über (1.3.1) ...
homeassistant-supervised (1.3.1) wird eingerichtet ...
[info] Restarting NetworkManager
[info] Restarting docker service
PING checkonline.home-assistant.io (104.26.5.238) 56(84) bytes of data.
64 bytes from 104.26.5.238 (104.26.5.238): icmp_seq=1 ttl=54 time=30.4 ms

--- checkonline.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 30.369/30.369/30.369/0.000 ms
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
[warn] Could not find /etc/default/grub or /boot/firmware/cmdline.txt failed to switch to cgroup v1
[info] Within a few minutes you will be able to reach Home Assistant at:
[info] http://homeassistant.local:8123 or using the IP address of your
[info] machine: http://192.168.2.160:8123
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ixperiencenl** [comment]
The same issue occurs on my fresh installed Ubuntu Server 22.04 NUC machine. This also prevents installing any addons etc. which is very frustrating since I switched over to supervised to be able to use the add-on functionality.

**Comment by Kanga-Who** [comment]
> The same issue occurs on my fresh installed Ubuntu Server 22.04 NUC machine. 

Ubuntu is not a supported OS

**Comment by ixperiencenl** [comment]
> > The same issue occurs on my fresh installed Ubuntu Server 22.04 NUC machine.
> 
> Ubuntu is not a supported OS

Great supportive comment.
By the way, I finally got it working by restarting Network Manager and Home Assistant.

**Comment by tdejneka** [comment]
> Great supportive comment.

It was a statement of fact. The only available official support is for Debian. Reference: [ADR-0014](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md)

If you want support for any other distro of Linux, try the community forum.

**Comment by basanisi** [comment]
I have the same problem vith debian 11.6 on raspi4.
Linux raspberrypi 5.15.84-v8+ #1610 SMP PREEMPT Mon Dec 19 18:54:50 GMT 2022 aarch64 GNU/Linux
It's a dns problem

**Comment by SammesV** [comment]
Also got this problem on Ubuntu. Before everyone goes ham on the OS, I know that debian is required, but I installed it a couple months ago on a Ubuntu install and that work. My question is, Is it true that it used to work on ubuntu and now it doesn't?

**Comment by frenck** [comment]
@SammesV Marked your comment as off-topic, as Ubuntu isn't supported by the Home Assistant project.

**Comment by ikifar2012** [comment]
Whats going on in the original issue is a failure to switch to cgroupv1
`Could not find /etc/default/grub or /boot/firmware/cmdline.txt failed to switch to cgroup v1`
I unfortunately do not have a Raspberry Pi to test with at the moment but was told by others that the location to edit `cmdline.txt` on Debian for Raspberry Pi is in `/boot/firmware/`, see #239. I have also seen some users report they see the file in `/boot/cmdline.txt` but most of them were on Raspberry Pi OS which is unsupported, so if you can confirm that you are in fact on an official Debian raspi image and the `cmdline.txt` file is in that directory I can add an additional check to the installer script

**Comment by igmerino** [comment]
On Debian for Raspberry Pi (64bit) the cmdline.txt is just in `/boot/` directory; so I was getting this error.

I managed to solve this issue by adding `systemd.unified_cgroup_hierarchy=0` at the end of `/boot/cmdline.txt` and copying `/boot/cmdline.txt` to `/boot/firmware/cmdline.txt`.

Hope this helps.

**Comment by henkiejan1** [comment]
You could bypass the OS check with the following command. You should know that Ubuntu is NOT supported by Home Assistant and you can not get support if you install on  Ubuntu. But it's for me personally working fine.

`sudo BYPASS_OS_CHECK=true dpkg -i homeassistant-supervised.deb`

**Comment by ixperiencenl** [comment]
Yes I know Ubuntu isn't supported, but you know some devs are so stubborn and just push their own will upon a computer ;)  Thanks for the suggestion!

**Comment by henkiejan1** [comment]
Hehe, the reason i post this is because i also run on Armbian/Ubuntu. At the moment on the Orangepi 5. Runs for ever without any problems on Armbian on the Orangepi 4. This command comes from the Home Assistant forum.

**Comment by SpartanTech** [comment]
Have been getting this error recently on 2 out of 3 of my boxes. One is running debian 11 supervised, one is running HassOS. My third box running debian 12 supervised does not give me the NetworkManager error.

Cmdline.txt in both /boot and /boot/firmware have systemd.unified_cgroup_hierarchy=false. Also having hassio errors on first boot that appeared around the same time.

All 3 boxes were fine until updated them from 2022 to 2023

**Comment by SpartanTech** [comment]
i have no issues with cgroup1 but still get NetworkManager error. Happens on 2 out of 3 of my boxes. All 3 of them were just upgraded to 2023 release this week. One runs HassOS, one runs Deb11 Sup and the 3rd (which is fine) runs Deb12 Sup.

Something else going on maybe. did what you said and made sure cmdline.txt is present at both /boot/cmdline.txt and /boot/firmware/cmdline.txt cgroup_hierarchy is set to false/0.

No cgroup errors show, only Network Manager. even the supervised script says successfully changed to v1 grub etc.

Network is working fine.
