### ISSUE TITLE
Bug Report: unable to find image for qemux86_64

### ISSUE THREAD

**Issue by lgwapnitsky** [home-assistant/supervised-installer#265]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux haos 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

### What happened?

Running in a proxmox VM, unable to get past HA initialization due to not being able to find a docker image for 22.12.6 for qemux86_64

### Machine Type

qemux86-64

### Relevant log output
```
22-12-16 19:50:00 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/qemux86-64-homeassistant:2022.12.6: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/home-assistant/qemux86-64-homeassistant:2022.12.6/json: Not Found ("no such image: ghcr.io/home-assistant/qemux86-64-homeassistant:2022.12.6: No such image: ghcr.io/home-assistant/qemux86-64-homeassistant:2022.12.6")
22-12-16 19:50:00 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retry in 30sec
22-12-16 19:50:30 INFO (SyncWorker_2) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:landingpage to ghcr.io/home-assistant/qemux86-64-homeassistant:2022.12.6
22-12-16 19:50:30 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2022.12.6.

```
### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
Are you 100% sure your DNS is working? try pinging `ghcr.io`
