### ISSUE TITLE
Bug Report: Block Unsupported OS (PR #262) violates ADR-0012 

### ISSUE THREAD

**Issue by lassem** [home-assistant/supervised-installer#266]
### OS Version

NA

### System Information

NA

### What happened?

Attempted to install in an unofficial way (Ubuntu 22.04) but got an error.
After much digging it turned out be be PR #262 which clearly violates ADR-0012 which says:

_The Home Assistant team will not prevent you from running Home Assistant using an unofficial method. However, we cannot help with issues that you encounter. We are open for contributions that improve compatibility with a community-supported method as long as they do not impact officially supported methods, add a significant amount of code exceptions or future maintenance burden on the Home Assistant development team._

I suggest you either roll back PR #262 or update the documentation.

https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md#decision

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frenck** [comment]
> The Home Assistant team will not prevent you from running Home Assistant using an unofficial method. 

You can still install it, the scripts are in this repository; feel free to run it and force install it on any system you like.
See: <https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/postinst>

I'm closing this issue, as per those same ADRs, your installation method is not supported by our project.

../Frenck
