### ISSUE TITLE
Raspbian GNU/Linux 11 (bullseye) is not supported! dpkg: error processing archive homeassistant-supervised.deb (--install)

### ISSUE THREAD

**Issue by pyzone2012** [home-assistant/supervised-installer#268]
Got this error on Raspberry Pi 4.
OS image : 2022-09-22-raspios-bullseye-armhf-lite.img.xz

Solved by use supervised-installer 1.3.1

**Comment by ikifar2012** [comment]
Yes this was solved in 1.3.1

**Comment by pyzone2012** [comment]
Sorry, I'm kinda newbie here  : I believed that the new issue belongs to the current version [1.4.1] by default.
It was with this latest version of the installer that I received this mistake and solved the problem using the old version for myself.
It turns out that the newest version tightens the requirements for the OS, so as not to allow the installation of HA-supervised in the Raspbian environment.
Sad situation...

**Comment by pyzone2012** [comment]
Matheson Steplock писал 2022-12-24 07:44:
> Yes this was solved in 1.3.1
> 
Sorry, I'm kinda newbie here : I believed that the new issue belongs to 
the current version [1.4.1] by default.
It was with this latest version of the installer that I received this 
mistake and solved the problem using the old version for myself.
It turns out that the newest version tightens the requirements for the 
OS, so as not to allow the installation of HA-supervised in the Raspbian 
environment.
Sad situation...
