### ISSUE TITLE
Bug Report: Fresh install fail on postinst script

### ISSUE THREAD

**Issue by francois09** [home-assistant/supervised-installer#270]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux proclos 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

### What happened?

When I launch install with the following command:

`DATA_SHARE=/opt/hassio dpkg -i /root/homeassistant-supervised.deb`

The postinst script fail at the following line:

https://github.com/home-assistant/supervised-installer/blob/77ba930b84ed274a201634e8139331f6d85fb4c6/homeassistant-supervised/DEBIAN/postinst#L125

complaining that `/opt/hassio/apparmor` directory doesn't exist.

I didn't keep output of my job, but I can reproduce it (a bit painful but...) if you really want the exact details.

Thanks in advance, and thanks for this really usefull product !

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by maps2002** [comment]
Hi @francois09 ,
I had the same issue.
In my case, I manually created the "apparmor" directory in the proper place, re-run the installer and it worked.
Thanks
