### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Gero670** [home-assistant/supervised-installer#272]
### OS Version

Debian 11

### System Information

Linux rpi3-20230102 6.0.0-6-arm64 #1 SMP Debian 6.0.12-1 (2022-12-09) aarch64 GNU/Linux

### What happened?

I have no idea on how  to overcome this

`2023-01-14 17:33:45 (865 KB/s) - 'homeassistant-supervised.deb.3' saved [6620/6620]

root@rpi3-20230102:~# dpkg -i homeassistant-supervised.deb
(Reading database ... 32856 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
/var/lib/dpkg/tmp.ci/preinst: line 15: lsb_release: command not found
dpkg: error processing archive homeassistant-supervised.deb (--install):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 127
[info] Undo divert on abort-install
No diversion 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised', none removed.
[info] Resetting debconf selections
[info] Removal complete, due to the complexity of this installation method,
[info] you will need to manually remove the containers created by the supervisor
Errors were encountered while processing:
 homeassistant-supervised.deb
`

### Machine Type

raspberrypi3-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
There was a new dependency added try, `sudo apt install lsb-release`

**Comment by Gero670** [comment]
it said it couldn't find any package with that name, something along the lines of "lsb-release has no installation candidate"

**Comment by ikifar2012** [comment]
> it said it couldn't find any package with that name, something along the lines of "lsb-release has no installation candidate"

That's very odd, can you confirm you have installed an official Debian Raspberry Pi image?  https://raspi.debian.net/tested-images/ The package should be available in the default repo

**Comment by Gero670** [comment]
i tried both with the 12 bookworm and after the 11 bullseye for my 3b+, had the same issue
