### ISSUE TITLE
Bug Report: Headless install hangs on Restarting NetworkManager

### ISSUE THREAD

**Issue by bjohas** [home-assistant/supervised-installer#273]
### OS Version

Ubuntu 22.04.1 LTS

### System Information

Linux ubuntu 5.15.0-1023-raspi #25-Ubuntu SMP PREEMPT Fri Jan 6 17:33:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### What happened?

An installation was interrupted. To fix it, I need to run
```
sudo dpkg --configure -a
``` 
However, I'm headless (Raspberry Pi), and connect via ssh. `dpkg` wants to restart the network manager, i.e., I get
```
[info] Restarting NetworkManager
```
and then the ssh connection hangs. 

On this page: https://peyanski.com/how-to-install-home-assistant-supervised-official-way/, a user called Tom (at 11/02/2022 at 3:34 pm) offer a solution.

They say: "The cause is that you’re probably using WiFi as connection. The installer is restarting the network interface and then not waiting for WiFi to reconnect first. Solution, add a delay in the installer script,"

Their suggestion is as follows:
```
sudo curl -Lo installer.sh https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh ”
```
Then edit the file [...]
```
info “Restarting NetworkManager
systemctl restart “${SERVICE_NM}
```
Add
```
info “Delay 20 seconds to give WiFi time to reconnect…..”
“sleep 20″
```
Resulting in:
```
info “Restarting NetworkManager
systemctl restart “${SERVICE_NM}
info “Delay 20 seconds to give WiFi time to reconnect…..”
sleep 20
```

Would it be possible to either add this to the installer, or perhaps add a warning to the installer?
```
info “Restarting NetworkManager
info “If you're headliess with ssh on wifi, this won't work, because wifi needs time to connect. Try on wired network instead or edit installation files. ”
systemctl restart “${SERVICE_NM}
```
Many thanks!

### Machine Type

raspberrypi3-64

### Installer output

```text
N/A
```

### Relevant log output

```shell
N/A
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
I wonder if there is a better way, perhaps we find a way to wait till it gets an IP address before continuing, not entirely sure how to approach that yet

**Comment by kahuitel** [comment]
Hi! I have some trouble finishing home assistant supervised install because of this behaviour (trying on a rpi zero 2w which only has wifi). Since URL provided by @bjohas seems to 404, I'm not sure how to proceed until a fix. Any idea?

Thanks!

**Comment by gbdavidx** [comment]
I am getting the same thing

**Comment by gbdavidx** [comment]
Not exact but diff, how can i fix this?

<img width="785" alt="Screenshot 2023-06-09 at 7 00 28 PM" src="https://github.com/home-assistant/supervised-installer/assets/26369204/f0ffb505-59ca-4d1e-8278-3ecc86f0ffd3">

**Comment by kenmaxnejp** [comment]
I am still getting the same problem when I try to upgrade my Raspberry Pi 4 to Ubuntu 24.04
