### ISSUE TITLE
home assistant supervised ghcr.io/home-assistant/aarch64-hassio-supervisor:2022.12.1 is missing locally

### ISSUE THREAD

**Issue by Bram-diederik** [home-assistant/supervised-installer#274]
I just discovered my Home assistant failover is down.

```
ghcr.io/home-assistant/aarch64-hassio-supervisor:2022.12.1
Error response from daemon: layer does not exist
```
Seams to be the problem

```
root@edita:/home/daft# /usr/sbin/hassio-supervisor
Error: No such object: hassio_supervisor
[WARNING] Supervisor container did not remove the startup marker file. Assuming 
container image or container corruption.
Error: No such container: hassio_supervisor
Error: No such image: 
[WARNING] Supervisor image missing, downloading a fresh one: 2022.12.1
2022.12.1: Pulling from home-assistant/aarch64-hassio-supervisor
Digest: sha256:6fb6cd5f7296efaf530369de422115236eb67cd0582a6ed3036deb7f8cfbe560
Status: Image is up to date for ghcr.io/home-assistant/aarch64-hassio-supervisor
:2022.12.1
ghcr.io/home-assistant/aarch64-hassio-supervisor:2022.12.1
Error response from daemon: layer does not exist
[INFO] Creating a new Supervisor container...
Error response from daemon: layer does not exist
```

**Comment by agners** [comment]
From the prompt assuming you are using Supervised, so transferring here.

This seems to be a very curious case of Docker image corruption. The start script tries to remove the image completely, but that fails (`Error: No such image: `), however, when trying to download a fresh copy, it seems to claim that the image already exists.


I'd try manually remove all docker images (check `docker images` for `supervisor` images) and remove them by using the image ID and `docker image rm --force <id>`.

**Comment by frenck** [comment]
PS: The image does exists <https://github.com/home-assistant/supervisor/pkgs/container/aarch64-hassio-supervisor/59564557?tag=2022.12.1>

**Comment by Bram-diederik** [comment]
Right. corruption I needed to remove my entire /var/lib/docker structure after being friendly.
System is restorted.
