### ISSUE TITLE
Install error : Raspbian GNU/Linux 10 (buster) is not supported!

### ISSUE THREAD

**Issue by auriou** [home-assistant/supervised-installer#276]
### OS Version

Raspbian GNU/Linux 10 (buster) 

### System Information

Linux raspberrypi 6.1.10-v7l+ #1629 SMP Wed Feb  8 10:54:09 GMT 2023 armv7l GNU/Linux

### What happened?

My Raspberry is in 32 bits
when I try to install the package I get this error

`
 sudo dpkg -i homeassistant-supervised.deb
`

### Machine Type

raspberrypi4

### Installer output

```text
(Lecture de la base de données... 121990 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
[error] Raspbian GNU/Linux 10 (buster) is not supported!
dpkg: erreur de traitement de l'archive homeassistant-supervised.deb (--install) :
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Undo divert on abort-install
Pas de détournement « détournement de /etc/NetworkManager/NetworkManager.conf en /etc/NetworkManager/NetworkManager.conf.real par homeassistant-supervised », aucun supprimé.
Pas de détournement « détournement de /etc/NetworkManager/system-connections/default en /etc/NetworkManager/system-connections/default.real par homeassistant-supervised », aucun supprimé.
Pas de détournement « détournement de /etc/docker/daemon.json en /etc/docker/daemon.json.real par homeassistant-supervised », aucun supprimé.
Pas de détournement « détournement de /etc/network/interfaces en /etc/network/interfaces.real par homeassistant-supervised », aucun supprimé.
[info] Resetting debconf selections
[info] Removal complete, due to the complexity of this installation method,
[info] you will need to manually remove the containers created by the supervisor
Des erreurs ont été rencontrées pendant l'exécution :
 homeassistant-supervised.deb
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frenck** [comment]
Raspbian is not supported indeed, only Debian 11 is.

This message is thus correct.

../Frenck

**Comment by auriou** [comment]
ok, thanks, sorry I didn't know. I will reinstall with Raspy PI OS.

**Comment by frenck** [comment]
Raspberry Pi OS is not supported. As said in my previous message as well, only Debian 11 is.

../Frenck

**Comment by auriou** [comment]
on this site they explain the installation with PI OS, the latest which is based on debian bullseye 11
https://www.diyenjoying.com/2022/09/22/install-home-assistant-supervisor-onto-raspberry-pi-4/

**Comment by frenck** [comment]
That link is also documentation not provided by the Home Assistant project, and thus not recommended.

> e installation with PI OS, the latest which is based on debian bullseye 11

That is not supported, as I already stated above. We only support Debian 11.

> It's possible to bypass pre-installaltion script ?

No, this installation script only works on supported systems. If you want to DIY your own, you can do so, but you are on your own (which is what unsupported means...).

../Frenck

**Comment by auriou** [comment]
ok, so you have to install version 11 on this page : https://raspi.debian.net/tested-images/

Version 12 does not work ?

THANKS

**Comment by frenck** [comment]
@auriou Debian 12 is not stable, but development (bookworm).

Please note (and please don't take this the wrong way), the Supervised installation method is the most advanced and complicated installation type we have. It is expected users of that installation method have extensive knowledge of Linux, Linux system administration, networking, container management, and so on. Considering your questions, I highly doubt you have that knowledge.

I would, therefore, highly and strongly recommend looking at one of the other installation methods we provide.

../Frenck

**Comment by auriou** [comment]
MDR, It's true that in 20 years of working in IT I still have a little trouble :)
