### ISSUE TITLE
Feature Request: Allow Ubuntu 22.04 installation

### ISSUE THREAD

**Issue by gairom** [home-assistant/supervised-installer#285]
### OS Version

Ubuntu 22.04.2 LTS

### System Information

Linux hass 5.15.0-1026-raspi #28-Ubuntu SMP PREEMPT Fri Mar 10 14:28:52 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### What happened?

Installer version 1.4 fails completely on Ubuntu if no older version is installed.
I worked around it by installing 1.3 first and then 1.4 which then work (supervisor version is updated) even though it produces the below errors.
This request is not about fully support Ubuntu installation (meaning fixing stuff in the supervisor), as the ADR describes this is not supported. The request is only about allowing the installer to run on Ubuntu and not fail.
Of course full support for Ubuntu will be awesome if possible but probably that will require new ADR  :-)
Tnx.

### Machine Type

raspberrypi4-64

### Installer output

```text
[error] Ubuntu 22.04.2 LTS is not supported!
dpkg: error processing archive homeassistant-supervised.deb (--install):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Restarting NetworkManager
[info] Restarting docker service
PING checkonline.home-assistant.io(2606:4700:20::ac43:445a (2606:4700:20::ac43:445a)) 56 data bytes
64 bytes from 2606:4700:20::ac43:445a (2606:4700:20::ac43:445a): icmp_seq=1 ttl=57 time=4.34 ms

--- checkonline.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.341/4.341/4.341/0.000 ms
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
[info] Within a few minutes you will be able to reach Home Assistant at:
[info] http://homeassistant.local:8123 or using the IP address of your
[info] machine: http://x.x.x.x:8123
Errors were encountered while processing:
 homeassistant-supervised.deb
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
Even though the OS check exists you can bypass it by setting changing the value for the BYPASS_OS_CHECK variable before executing the installer https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/preinst#LL14C1-L14C42
