### ISSUE TITLE
Bug Report: Home Assistant UI not opening after Restore on HA Supervised running on Debian OS

### ISSUE THREAD

**Issue by GitWally** [home-assistant/supervised-installer#289]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux iWallyHP 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### What happened?

Don't know if it is the right place, but can't find other 

I'm trying to migrate from RPi where HA Supervised was running to NUC with Debian with HA Supervised.

![image](https://user-images.githubusercontent.com/19230076/234647528-1289f362-fab0-4a7e-933f-22948acf3814.png)

Installation was fine, but after restore of backup Home Assistant UI is not responding (despite port 8123 being opened):

![image](https://user-images.githubusercontent.com/19230076/234648177-5550a412-e190-4dff-b695-c081dce980a7.png)

while observer is responding with green!

![image](https://user-images.githubusercontent.com/19230076/234648439-0f43b6c5-0127-42b8-862b-03aca74f0333.png)

I found no relevant logs (to address further investigations) in:

```shell
ha core logs
``` 
or

```shell
ha supervisor logs
``` 

Don't know what else I could to to solve the issue
Thanks

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
This seems like less of a bug and more of a support issue, please head on over to the [discord](https://www.home-assistant.io/join-chat/) I'd be happy to help you there
