### ISSUE TITLE
Bug Report: Clean install instals supervisor version 2023.05.dev3103. Can't restore backup from 2023.05.0.

### ISSUE THREAD

**Issue by jsiemek** [home-assistant/supervised-installer#292]
### OS Version

Debian GNU/Linux 11 

### System Information

 Linux ha 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

### What happened?

Installation of beta 2023.6.0b0 went faulty. 
So, I'd like to resotre last backup of 2023.5.4.
I wiped the installation, removed all containers and images.
Made clean install using:
`apt install ./homeassistant-supervised.deb`
Then upload backup and tried to restore.
Got error message:
**ERROR (MainThread) [supervisor.backups.manager] Backup was made on supervisor version 2023.05.0, can't restore on 2023.05.dev3103. Must update supervisor  **

### Machine Type

generic-x86-64

### Installer output

```text
nothing specific
```

### Relevant log output

```shell
ERROR (MainThread) [supervisor.backups.manager] Backup was made on supervisor version 2023.05.0, can't restore on 2023.05.dev3103. Must update supervisor
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by vgisbert** [comment]
Hello. I'm with the same problem.

ERROR (MainThread) [supervisor.backups.manager] Backup was made on supervisor version 2024.01.0.dev1902, can't restore on 2023.12.1. Must update supervisor first.

Has anyone managed to solve it?
Can the supervisor be downgraded?
