### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by mr-aliftin** [home-assistant/supervised-installer#294]
### OS Version

Ubuntu 22.04.2 LTS

### System Information

Linux orangepiplus2e 6.1.30-sunxi #1 SMP Wed May 24 16:32:53 UTC 2023 armv7l armv7l armv7l GNU/Linux

### What happened?

Hi all.
Trying to install "homeassistant-supervised.deb" on my  orangepi+ 2e but running into a problem. How to solve it?

### Machine Type

qemuarm

### Installer output

```text
root@orangepiplus2e:~# dpkg -i ./homeassistant-supervised.deb
(Reading database ... 38606 files and directories currently installed.)
Preparing to unpack ./homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
[error] Ubuntu 22.04.2 LTS is not supported!
dpkg: error processing archive ./homeassistant-supervised.deb (--install):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Undo divert on abort-install
No diversion 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised', none removed.
[info] Resetting debconf selections
[info] Removal complete, due to the complexity of this installation method,
[info] you will need to manually remove the containers created by the supervisor
Errors were encountered while processing:
 ./homeassistant-supervised.deb
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Kanga-Who** [comment]
Ubuntu is not supported, read the ADR you have ticked you have read.

**Comment by mr-aliftin** [comment]
it's very sad

**Comment by Kanga-Who** [comment]
> it's very sad

It's been this way for 2+ years, it's not new information.

**Comment by mr-aliftin** [comment]
If I had read the instructions, my life would have been much more boring. Thanks for the quick response.
