### ISSUE TITLE
Bug Report: Debian 12 not listed as supported OS

### ISSUE THREAD

**Issue by yiweiyu32** [home-assistant/supervised-installer#296]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux j5040 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

### What happened?

I upgraded the OS that home assistant is installed on (supervised mode) from Debian 11 to Debian 12 and I get a notice from within home assistant that my OS is "Unsupported system - Operating System". 
Now that Debian 12 has been officially released, we should start tracking the progress of home assistant supervised supporting Debian bookworm.

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frangigu** [comment]
I get these three errors/repair after upgrade from Debian 11 to 12. Can't manage to fix Systemd-Resolved & Systemd Journal
![image](https://github.com/home-assistant/supervised-installer/assets/95890417/2139de11-f2f3-4e52-97e3-19ae0882f32a)

**Comment by Kanga-Who** [comment]
Read the ADR guys, c'mon.

_'Debian Linux Debian 11 aka Bullseye (no derivatives)'_

**Comment by yiweiyu32** [comment]
> Read the ADR guys, c'mon.
> 
> _'Debian Linux Debian 11 aka Bullseye (no derivatives)'_

I did but still thought this was the best place to raise the Debian 12 ticket.

**Comment by Kanga-Who** [comment]
> > Read the ADR guys, c'mon.
> > _'Debian Linux Debian 11 aka Bullseye (no derivatives)'_
> 
> I did but still thought this was the best place to raise the Debian 12 ticket.

So you're raising a ticket for an OS that is no supported, when the ADR tells what is supported and what isn't?

**Comment by Kanga-Who** [comment]
As per the ADR, the next version of Debian will be added as supported in due course.

Until then, the only supported OS is Debian 11.

**Comment by hiddesteenbeek** [comment]
Quick question from a bit of a github noob, I understand that this bug report was closed yesterday (https://github.com/home-assistant/supervisor/pull/4377). However, when I now try to install the supervisor on Debian 12 bookworm, I still get the following error:

`[error] Debian GNU/Linux 12 (bookworm) is not supported!
dpkg: error processing archive /home/user/homeassistant-supervised.deb (--unpack):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Undo divert on abort-install
`

Am I too quick in trying to install it and should I wait more time for the changes as made in the pull request to have effect? Thanks in advance!

**Comment by frenck** [comment]
Software needs to be released... you are looking at the development here.
It will be part of the next stable release (there is no specific timeline for that).

../Frenck

**Comment by yiweiyu32** [comment]
I understand that there is no specific timeline for the next stable release, but when is that typically determined?

> Software needs to be released... you are looking at the development here. It will be part of the next stable release (there is no specific timeline for that).
> 
> ../Frenck
