### ISSUE TITLE
Bug Report: Debian 12 (bookworm) support

### ISSUE THREAD

**Issue by guice** [home-assistant/supervised-installer#299]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux venus-ha 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

### What happened?

Debian 12 (bookworm) is now the default install for Debian. It was released on June 10th, and superseded Debian 11 (bullseye). The supervisor package current is not setup to support Debian 12, thus blocking the ability to install.

### Machine Type

generic-x86-64

### Installer output

```text
user@ha:~/Downloads » sudo apt install ./homeassistant-supervised.deb  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'homeassistant-supervised' instead of './homeassistant-supervised.deb'
The following NEW packages will be installed:
  homeassistant-supervised
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/6,456 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/pz/Downloads/homeassistant-supervised.deb homeassistant-supervised all 1.4.3 [6,456 B]
Preconfiguring packages ...
(Reading database ... 153724 files and directories currently installed.)
Preparing to unpack .../homeassistant-supervised.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[error] Debian GNU/Linux 12 (bookworm) is not supported!
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by guice** [comment]
Do add on my end: I'm on site only for a few days. I'm building a new system, and this is blocking. I'm trying to get Debian 11 installed, but running into issues with the install recognizing the USB install. 

In short: I'm currently "stuck" on Debian 12. Is there anyway to force install as Debian 12 doesn't seemed to have changed enough to break support for the package?

**Comment by ikifar2012** [comment]
I am currently waiting on the new version of the supervisor to be released which includes my change to mark Debian 12 as supported. I was waiting to release the installer package on the day the supervisor gets released, I will try to get an ETA on that but for now you can bypass the requirements by changing the env var $BYPASS_OS_CHECK to true

**Comment by guice** [comment]
I'm happy to report this was a success. Thank you! 

One note for those finding this: I had to create a login, dismiss "unsupported system" errors and warnings, and manually restart supervisor (`docker restart hassio_supervisor`) in order to get backup restores working with this "hack." I'm happy to report HA backup restored flawlessly, too.

I'm up and running -- on Debian 12!

**Comment by carpcat** [comment]
> I am currently waiting on the new version of the supervisor to be released which includes my change to mark Debian 12 as supported. I was waiting to release the installer package on the day the supervisor gets released, I will try to get an ETA on that but for now you can bypass the requirements by changing the env var `$BYPASS_OS_CHECK` to true

Can I ask how you get to the env var to change? Thanks

**Comment by guice** [comment]
> Can I ask how you get to the env var to change? Thanks

I just added it to the CLI call like this:

```
sudo BYPASS_OS_CHECK=true apt install ./homeassistant-supervised.deb  
```

You need to pass it after sudo, or do it as root, since sudo creates a sub-term to run the commands.

**Comment by ByungGoo** [comment]
Thanks and It's very helpful.

**Comment by timj-pdx** [comment]
You could always install Debian 11, install HA, then upgrade to Debian 12 after HA is installed and running. I've been running  HA supervised (2030.6.2)  on Debian 11 for some time. I am just planning to update to Debian 12 using the normal Debian process (edit 'sources.llist' ; apt update ; apt full-upgrade)  with HA in place.

**Comment by dMopp** [comment]
Note: Supervised brings some issues with apparmor. I was forced to disable apparmor for now :/

**Comment by RohitJones** [comment]
If anyone is having issues restoring their backups and sees the log 
`INFO (MainThread) [supervisor.jobs] 'BackupManager.do_restore_full' blocked from execution, no host internet connection` 
in their "hassio_supervisor" container, the following commands fixed the issue for me.
```
ha dns options --servers dns://1.1.1.1
ha dns restart
ha net reload
```

**Comment by hitnrun30** [comment]
> > Can I ask how you get to the env var to change? Thanks
> 
> I just added it to the CLI call like this:
> 
> ```
> sudo BYPASS_OS_CHECK=true apt install ./homeassistant-supervised.deb  
> ```
> 
> You need to pass it after sudo, or do it as root, since sudo creates a sub-shell to run the commands.

Can this be done without do a fresh install?

**Comment by abmantis** [comment]
This is in conflict with the documentation, that states that only Debian 12 is supported: https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md

**Comment by ffries** [comment]
I can confirm that installing under Debian 12.1 works like a charm (except systemd-resolved). Congratulations for working on this "managed" installer. I am quite surprised to see how easy it is to implement and upgrade docker images over-the-air.
