### ISSUE TITLE
variable $os not exist

### ISSUE THREAD

**Issue by miorba** [home-assistant/supervised-installer#300]
https://github.com/home-assistant/supervised-installer/blame/06671c39bd5c81fd213330597fbf9c7dd9a36e78/homeassistant-supervised/DEBIAN/preinst#L21

The variable indicated in the "if" function is not correct. you should use supported_os. Please check

**Comment by ikifar2012** [comment]
`$os` is defined in the for loop
https://github.com/home-assistant/supervised-installer/blame/06671c39bd5c81fd213330597fbf9c7dd9a36e78/homeassistant-supervised/DEBIAN/preinst#L20
