### ISSUE TITLE
Bug Report: the site:checkonline.home-assistant.io couldn't be ping by users in china.

### ISSUE THREAD

**Issue by abirvepete** [home-assistant/supervised-installer#305]
### OS Version

debian 11

### System Information

linux 5.15

### What happened?

the site:checkonline.home-assistant.io couldn't be ping by users in china.
recent days i try to install superevised,but at the last step "apt install ./homeassistant-supervised.deb",couldn't finish the set up .
because my pc couldn't ping "checkonline.home-assistant.io",which leads to my pc restart the script again and again
i check if the site can be accessed through ip ping.
so what happened to your check site,could upgrde for the chinese users?
![image](https://github.com/home-assistant/supervised-installer/assets/86662432/e644405e-558b-4fd6-958c-1a2479b9f09e)
![image](https://github.com/home-assistant/supervised-installer/assets/86662432/4663f18e-b59c-4d76-a9f3-f95dce05d0c8)

### Machine Type

generic-x86-64

### Installer output

```text
pass
```

### Relevant log output

```shell
pass
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by yinjy0** [comment]
I have a same problem.

**Comment by ikifar2012** [comment]
So you are unable to ping `version.home-assistant.io` even from another pc?

**Comment by mapmiss** [comment]
I have the same problem, is there a solution?

**Comment by mapmiss** [comment]
> So you are unable to ping `version.home-assistant.io` even from another pc?

Yes, another pc are unable to ping.

**Comment by ikifar2012** [comment]
Just to be clear here, all users commenting on this issue are from China?
Normally I would close this issue since it appears the original post is from an armbian install which is not supported but given you can't even ping  `version.home-assistant.io` from another computer this is not an issue with the installer
I would recommend everyone try to use [1.1.1.1](https://1.1.1.1/) by Cloudflare it appears to be available in China 

I am going to tag in the @home-assistant/supervisor team here to see if they have any input

**Comment by abirvepete** [comment]
thank you.Normally homeassistant's webs and subwebs can't be banned by China,but still happenned,i don't konw what was the reason,but the DNS can be a alternative.

**Comment by abirvepete** [comment]
oh,the sit could be ping right now.but i hope that it will  not happen again.可以用了兄弟们
