### ISSUE TITLE
Docker priviledged Issues

### ISSUE THREAD

**Issue by knebb** [home-assistant/supervised-installer#307]
### Feedback

Sorry, this is not helpful.

I have a fresh installation on DEbian12 which is supposed to be the only Debian version currently supported. (the supervisor install page tells to install systemd-resolved which is not available on Debian11).

However, I am getting the above error when installing and both hints are not helpfule (have the latest up-to-date OS and run the installation just recently).

I found the following page but I am not sure if this patches. At least I did not find any user to add to the docker group....
https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

### URL

https://www.home-assistant.io/more-info/unhealthy/privileged/

### Version

2023.6.3

### Additional information

Freshly installed. Bookworm Deb 12

**Comment by ikifar2012** [comment]
The supervisor is configured to run as privileged, I did notice this issue on one of my machines but it was resolved with a reboot. I also noticed some issues with running older os-agent versions on Debian 12 so please make sure you are using the latest version of the os agent and that you have rebooted the system at least once

**Comment by oli-f** [comment]
I had the same issue when upgrading from Debian 11 to Debian 12. However a simple reboot made the notification disappear.

**Comment by abmantis** [comment]
For me updating the os-agent, reinstalling the superviser deb and rebooting fixed it.

**Comment by ffries** [comment]
Rebooting fixed the issue. I was also quite annoyed to loose SSH connection to the server. I understand that this is "managed" but it seems that I am loosing all control. I still have serial console access, but loosing SSH is strange.
