### ISSUE TITLE
Installation on RaspberryPi 4 with plain Debian 12 bookworm fails with exit status 1

### ISSUE THREAD

**Issue by laurencijs** [home-assistant/supervised-installer#310]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux homeassistant 6.1.0-9-arm64 #1 SMP Debian 6.1.27-1 (2023-05-08) aarch64 GNU/Linux

### What happened?

Hello!

Having RaspberryPi 4 with _plain_ Debian 12 installed. (Not a Raspberry OS)
I'm trying to set up a supervisor in this system, but the installation failed with the error, please take a look at the installer output. 

The same happens if trying to install using apt, all prerequisites are installed as per documentation.
The system is installed on the USB SSD disk not on SD card.

### Machine Type

raspberrypi4-64

### Installer output

```text
dpkg -i homeassistant-supervised.deb
(Reading database ... 57576 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
Leaving 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Leaving 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassist'
Leaving 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Leaving 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.5.0) over (1.5.0) ...
Setting up homeassistant-supervised (1.5.0) ...
[info] Restarting NetworkManager
[info] Set up systemd-journal-gatewayd socket file
[info] Enable systemd-journal-gatewayd
dpkg: error processing package homeassistant-supervised (--install):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 homeassistant-supervised
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by agners** [comment]
Hm, it is not quite clear to me why the installation script fails. Can you run these commands manually and check/post their output?

```
systemctl enable systemd-journal-gatewayd.socket
systemctl start systemd-journal-gatewayd.socket
```
