### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by ffries** [home-assistant/supervised-installer#316]
### OS Version

Debian GNU/Linux (Bookworm)

### System Information

Latest

### What happened?

SSL https certificate is too long:

Une erreur est survenue pendant une connexion à 192.xxx.xxx.xxx:8123. SSL a reçu un enregistrement qui dépasse la longueur maximale autorisée.

(SSL certificate exceeds the maximum lenght and is too long)

Code d’erreur : SSL_ERROR_RX_RECORD_TOO_LONG

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by mikka2** [comment]
Is this Firefox? Try rebooting HA machine after installation or use another web-browser.
