### ISSUE TITLE
Debian 12 install error

### ISSUE THREAD

**Issue by stevenliuit** [home-assistant/supervised-installer#317]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux armbian 6.1.50-current-rockchip64 #3 SMP PREEMPT Wed Aug 30 14:11:13 UTC 2023 aarch64 GNU/Linux

### What happened?

i install armbian bookworm version but install supervised error：
Download is performed unsandboxed as root as file '/home/steven/homeassistant-supervised.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

### Machine Type

qemuarm-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by MaxWinterstein** [comment]
Are you sure this is the correct error displayed? This smells like you try to install on some 'unsupported' os. Full install log might help here.

I take a wild guess and go with
```bash
BYPASS_OS_CHECK=true apt install ./homeassistant-supervised.deb
```

**Comment by frenck** [comment]
> Linux armbian 


Armbian is not supported. Please make sure you read the requirements for this installation method.

../Frenck
