### ISSUE TITLE
Bug Report: Depends: systemd-resolved but it is not installable

### ISSUE THREAD

**Issue by amitsamanta996** [home-assistant/supervised-installer#323]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### What happened?

Installed with
`sudo dpkg -i --ignore-depends=systemd-resolved homeassistant-supervised.deb`
all good with home assistant, but when trying to do anything with apt-get
`You might want to run 'apt --fix-broken install' to correct these.`
`The following packages have unmet dependencies:`
` homeassistant-supervised : Depends: systemd-resolved but it is not installable`
`E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).`

You guys needs to understand people do other stuff in one server not dedicate entirely for just home assistant.
Please have a fix for this

### Machine Type

raspberrypi4-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Lockszmith-GH** [comment]
See [my answer to #321](https://github.com/home-assistant/supervised-installer/issues/321#issuecomment-1732567582)

**Comment by amitsamanta996** [comment]
thanks, Updating debian fixed the issue,
you should allow other docker containers to run like pihole, portainer, etc and not show the system is unhealthy (just a suggestion)

**Comment by Aleksahek** [comment]
```
apt install ./homeassistant-supervised.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'homeassistant-supervised' instead of './homeassistant-supervised.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 systemd-resolved : Depends: systemd (= 252.5-2~bpo11+1) but 247.3-7+deb11u4 is to be installed
                    Breaks: systemd (< 251.3-2~) but 247.3-7+deb11u4 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Update is not help me.

How to fix it?

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by Lockszmith-GH** [comment]
Note that  you're riding another's issue - but, I'll try and help.

You havn't upgraded to Debian 12.
Are you experiencing any issues upgrading to Debian 12?

**Comment by weksupport** [comment]
We have the same problem

With Superviser 1.4.3 (not 1.5.0 the latest) It works fine !!

We have Debian 11

**Comment by Lockszmith-GH** [comment]
That is correct, for latest supervisor you must first upgrade your debian.

Follow the link, and follow the instructions. This solved the issue for OP ([amitsamanta996](https://github.com/amitsamanta996)), I'm sure it will solve it for you as well.
The link will also provide you with all the 'why' this works.

> See [my answer to #321](https://github.com/home-assistant/supervised-installer/issues/321#issuecomment-1732567582)

**Comment by ikifar2012** [comment]
The fix is pending release

**Comment by ikifar2012** [comment]
This issue was fixed in https://github.com/home-assistant/supervised-installer/releases/tag/1.6.0

**Comment by Venodor** [comment]
Debian12 on PC
dpkg: ошибка при обработке пакета homeassistant-supervised (--configure):
 подпроцесс из пакета homeassistant-supervised установлен сценарий post-installation возвратил код ошибки 1
При обработке следующих пакетов произошли ошибки:
 homeassistant-supervised
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by agners** [comment]
@Venodor please english comments only. Also make sure to search community forums and issues, this seems like a problem reported elsewhere already.
