### ISSUE TITLE
Bug Report: kernel.perf_event_paranoid setting

### ISSUE THREAD

**Issue by wimb0** [home-assistant/supervised-installer#338]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux optiplex 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

### What happened?

Supervisor was updated to allow addons to use CAP_BPF and CAP_PERFMON.
(https://github.com/home-assistant/supervisor/pull/4130)
Addons that use these capabilities, such as the latest [Frigate Beta](https://github.com/blakeblackshear/frigate/issues/8494), do not work correctly on Supervised installs on Debian.
This seems to be because HAOS has a default `kernel.perf_event_paranoid=2` setting while Debian 11 and Debian 12 have a default of `kernel.perf_event_paranoid=3`.

I think that it would be great to add `sysctl kernel.perf_event_paranoid=2` to the supervised installer script.

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by marcgarciamarti** [comment]
> Does not seem to be relevant anymore.

For me change the value to 2, did indeed do the trick! I'm glad I bumped into this!!
