### ISSUE TITLE
Support for RPi 5?

### ISSUE THREAD

**Issue by InfiniteBSOD** [home-assistant/supervised-installer#347]
Hello,

Wondering if the supervised alternative is supported on Raspberry Pi 5?

RPi 5 isn't listed under "Supported machine types":
https://github.com/home-assistant/supervised-installer?tab=readme-ov-file#supported-machine-types

Best Regards

**Comment by Naturalien** [comment]
There is a fork that has the Pi5 supported. Also an Pull request has been created. Not 100% sure why it isn't merged.

https://github.com/home-assistant/supervised-installer/pull/345

**Comment by frenck** [comment]
> Not 100% sure why it isn't merged.

The base images do not have the proper support yet. Expected it that those will be used as of 2024.2.

**Comment by HonzaJaros** [comment]
Hi,

with the 2024.2 already Out, when installer get its update please?

**Comment by frenck** [comment]
>  already Out

Lol that makes it sound like it has already been out for ages, the reality is that it hasn't even been out for 24 hours yey...  😉

**Comment by HuckleberryLovesYou** [comment]
I've made an tutorial about this in my Github Repository. It may help you:
https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5

**Comment by frenck** [comment]
Shipped in: https://github.com/home-assistant/supervised-installer/releases/tag/1.7.0
