### ISSUE TITLE
Bug Report: Automation, After/Before Date (only) in condition does not work. Alway Passes conditin test.

### ISSUE THREAD

**Issue by shdashley** [home-assistant/supervised-installer#348]
### OS Version

bash: lsb_release: command not found

### System Information

Linux core-ssh 6.1.63-haos-raspi #1 SMP PREMPT Tue Jan  9 10:42:51 UTC 2024 aarch64 Linux

### What happened?

Setting up Date/Time Helpers (2 of them one for Start date and One Stop date). Adding these helpers to an automation 'condition'. Both start and stop dates are in the future. I expected that the condition would fail the 'test'. But the condition passes when it should not. I had set the 'start' helper to 1-April-2024 and 'stop' helper to 16-October-2024. At this time forme these dates are in the future, and I expected the condition to fail.

![HAOS-Date_time_in_future-Fails](https://github.com/home-assistant/supervised-installer/assets/110645418/1dc2f917-a3e6-41eb-8c0a-242af469b970)

### Machine Type

raspberrypi4-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frenck** [comment]
Hi there @shdashley 👋 

It seems like you want to report an issue with Home Assistant itself, however, you have submitted an issue in the issue tracker for the Supervised installer. Please submit issues with Home Assistant Core here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by shdashley** [comment]
Taa, Sorry.
