### ISSUE TITLE
Bug Report: the supervisor doesn't have docker's super privileges.

### ISSUE THREAD

**Issue by zuobianfy** [home-assistant/supervised-installer#353]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux homeassistant 6.3.13-rockchip64 #1 SMP PREEMPT Tue Jul 11 19:39:51 CEST 2023 aarch64 GNU/Linux

### What happened?

Every time supervisor is upgraded, homeassistant's page gets an unhealthy permissions error. Basically, the supervisor doesn't have docker's super privileges. But docker restart hassio_supervisor does not report this error. But the supervisor will show up the next time it's upgraded. This is usually caused by something.

### Machine Type

qemuarm-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Lockszmith-GH** [comment]
Seems like a duplicate of #342 (see that for my own personal solution).
Which is a duplicate of [home-assistant/supervisor #4381](https://github.com/home-assistant/supervisor/issues/4381).

**Comment by zuobianfy** [comment]
> Seems like a duplicate of #342 (see that for my own personal solution). Which is a duplicate of [home-assistant/supervisor #4381](https://github.com/home-assistant/supervisor/issues/4381).

Thanks a million!
