### ISSUE TITLE
Add riscv64 release

### ISSUE THREAD

**Issue by eshattow** [home-assistant/supervised-installer#363]
### OS Version

Debian GNU/Linux trixie/sid

### System Information

Linux you 6.7.9-riscv64 #1 SMP Debian 6.7.9-2 (2024-03-13) riscv64 GNU/Linux

### What happened?

I would like to install Home Assistant supervised on Debian official riscv64 architecture (Home Assistant Yellow PoE with Milk-V Mars CM Lite). There is an official daily build of debian-installer now for this architecture at https://d-i.debian.org/daily-images/riscv64/ which works well on this hardware and so now ready for the next step to see support in Home Assistant for this architecture. Thanks!

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frenck** [comment]
The Home Assistant project doesn't support the riscv64 architecture.

It can does not be added to the installer.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
