### ISSUE TITLE
Bug Report: debian 12 error install

### ISSUE THREAD

**Issue by lokomass** [home-assistant/supervised-installer#374]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux debian 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux

### What happened?

Hi,
here is all commands I send to a new debian 12 installation (with dns tips)

```
RESOLV="/etc/systemd/resolved.conf.d"
DNS=$(cat /etc/resolv.conf | sed "s/nameserver //g")
PACKAGES=( 	"bluez" 	"udisks2" 	"cifs-utils" 	"nfs-common" 	"libglib2.0-bin" 	"network-manager" 	"systemd-resolved" 	"systemd-journal-remote" )
LISTE=""
for ((I=0;I<${#PACKAGES[@]};++I)); 	do 		LISTE+=" ${PACKAGES[$I]}"; 	done
apt install${LISTE} -y
mkdir $RESOLV
echo -e "[Resolve]\nDNS=${DNS}\nDNSStubListener=no" > $RESOLV/resolved.conf
systemctl restart systemd-resolved
AGENT="https://api.github.com/repos/home-assistant/os-agent/releases/latest"
VERSION=$(curl -s "$AGENT" | jq -r ".tag_name")
DEB="os-agent_${VERSION}_linux_x86_64.deb"
curl -fsSL get.docker.com | sh

AGENT="https://api.github.com/repos/home-assistant/os-agent/releases/latest"
VERSION=$(curl -s "$AGENT" | jq -r ".tag_name")
DEB="os-agent_${VERSION}_linux_x86_64.deb"
wget https://github.com/home-assistant/os-agent/releases/download/$VERSION/$DEB
dpkg -i $DEB

DEB="homeassistant-supervised.deb"
wget https://github.com/home-assistant/supervised-installer/releases/latest/download/$DEB
BYPASS_OS_CHECK=true apt install ./$DEB
```

### Machine Type

qemux86-64

### Installer output

```text
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Note : sélection de « homeassistant-supervised » au lieu de « ./homeassistant-supervised.deb »
Les NOUVEAUX paquets suivants seront installés :
  homeassistant-supervised
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/7 440 o dans les archives.
Après cette opération, 0 o d'espace disque supplémentaires seront utilisés.
Réception de :1 /root/homeassistant-supervised.deb homeassistant-supervised all 1.8.0 [7 440 B]
Préconfiguration des paquets...                 
Sélection du paquet homeassistant-supervised précédemment désélectionné.
(Lecture de la base de données... 40022 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../homeassistant-supervised.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
[info] Fix kernel dmesg restriction
Ajout de « détournement de /etc/NetworkManager/NetworkManager.conf en /etc/NetworkManager/NetworkManager.conf.real par homeassistant-supervised »
Ajout de « détournement de /etc/NetworkManager/system-connections/default en /etc/NetworkManager/system-connections/default.real par homeassistant-supervised »
Ajout de « détournement de /etc/docker/daemon.json en /etc/docker/daemon.json.real par homeassistant-supervised »
Ajout de « détournement de /etc/network/interfaces en /etc/network/interfaces.real par homeassistant-supervised »
Ajout de « détournement de /etc/systemd/resolved.conf en /etc/systemd/resolved.conf.real par homeassistant-supervised »
Dépaquetage de homeassistant-supervised (1.8.0) ...
Paramétrage de homeassistant-supervised (1.8.0) ...
[info] Reload systemd
[info] Restarting NetworkManager
[info] Enable systemd-resolved
[info] Restarting systemd-resolved
[info] Set up systemd-journal-gatewayd socket file
[info] Enable systemd-journal-gatewayd
[info] Start nfs-utils.service
[info] Restarting docker service
PING checkonline.home-assistant.io (104.26.5.238) 56(84) bytes of data.
64 bytes from 104.26.5.238 (104.26.5.238): icmp_seq=1 ttl=55 time=17.2 ms

--- checkonline.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 17.188/17.188/17.188/0.000 ms
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
[info] Switching to cgroup v1
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.1.0-22-amd64
Found initrd image: /boot/initrd.img-6.1.0-22-amd64
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
done
[info] Within a few minutes you will be able to reach Home Assistant at:
[info] http://homeassistant.local:8123 or using the IP address of your
[info] machine: http://192.168.100.15:8123
[warn] A reboot is required to apply changes to grub.
N: Le téléchargement est effectué en dehors du bac à sable en tant que « root » car le fichier « /root/homeassistant-supervised.deb » n'est pas accessible par l'utilisateur « _apt ». - pkgAcquire::Run (13: Permission non accordée)
```

### Relevant log output

```shell
root@debian:~# journalctl -f
juil. 05 22:10:16 debian hassio_dns[7541]: [INFO] 172.30.32.1:45671 - 26787 "PTR IN 248.100.168.192.in-addr.arpa. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.042297226s
juil. 05 22:10:16 debian hassio_dns[7541]: [INFO] 172.30.32.1:45671 - 10474 "PTR IN 247.100.168.192.in-addr.arpa. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.042586445s
juil. 05 22:10:16 debian hassio_dns[7541]: [INFO] 172.30.32.1:45671 - 28499 "PTR IN 218.100.168.192.in-addr.arpa. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.050056144s
juil. 05 22:12:33 debian qemu-ga[452]: info: guest-ping called
juil. 05 22:12:34 debian qemu-ga[452]: info: guest-ping called
juil. 05 22:12:34 debian sshd[10094]: Accepted publickey for root from 192.168.100.170 port 33814 ssh2: RSA SHA256:4fvYrHiwhZCLiYoIFYS8ASX0ZRIG0tmEhlZnfs4SJTY
juil. 05 22:12:34 debian sshd[10094]: pam_unix(sshd:session): session opened for user root(uid=0) by (uid=0)
juil. 05 22:12:34 debian systemd-logind[455]: New session 5 of user root.
juil. 05 22:12:34 debian systemd[1]: Started session-5.scope - Session 5 of User root.
juil. 05 22:12:34 debian sshd[10094]: pam_env(sshd:session): deprecated reading of user environment enabled
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Frankynov** [comment]
Hello,
A bit a newbie here but I ran into the same issue yesterday when trying to install Home Assistant supervised on Debian 12.
So what I did, I deleted the alias of : /etc/resolv.conf (which is on that location) and created a new one, with : 
`nameserver 8.8.8.8`
This should allow the installer to work (do a ping of a web domain first to confirm)
After the installation finished, I headed into the system settings of Home Assistant, and noticed that in the network config, the DNS field was blank. Enter the one you want.
After a reboot it should persist.
I suspect there is maybe some kind of issue with the network manager package which comes with the pre-requirements of the installation but wild guess here.

**Comment by litinoveweedle** [comment]
Same issue, fixed by filling dns into `DNS=` in the `/etc/systemd/resolved.conf` and reboot

This issue happens also during the `homeassistant-supervised.deb` package upgrade/reinstall.

**Comment by samec051** [comment]
Same thing 🚨 
`Jul 16 12:47:48 rockpi-4a hassio_supervisor[3239]: 2024-07-16 12:47:48.517 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
Jul 16 12:47:48 rockpi-4a hassio_supervisor[3239]: 2024-07-16 12:47:48.518 WARNING (MainThread) [supervisor.plugins.base] Error on installing cli plugin, retrying in 30sec
Jul 16 12:47:48 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:48.858847913+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:52367" dns-server="udp:8.8.8.8:53" error="read udp 172.17.0.2:52367->8.8.8.8:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t AAAA"
Jul 16 12:47:48 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:48.860301867+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:49354" dns-server="udp:8.8.8.8:53" error="read udp 172.17.0.2:49354->8.8.8.8:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t A"
Jul 16 12:47:50 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:50.015171748+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:58872" dns-server="udp:8.8.4.4:53" error="read udp 172.17.0.2:58872->8.8.4.4:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t AAAA"
Jul 16 12:47:50 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:50.015377081+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:35333" dns-server="udp:8.8.4.4:53" error="read udp 172.17.0.2:35333->8.8.4.4:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t A"
Jul 16 12:47:51 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:51.515765242+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:55911" dns-server="udp:8.8.8.8:53" error="read udp 172.17.0.2:55911->8.8.8.8:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t A"
Jul 16 12:47:51 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:51.516107032+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:36909" dns-server="udp:8.8.8.8:53" error="read udp 172.17.0.2:36909->8.8.8.8:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t AAAA"
Jul 16 12:47:54 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:54.017207188+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:46408" dns-server="udp:8.8.8.8:53" error="read udp 172.17.0.2:46408->8.8.8.8:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t AAAA"
Jul 16 12:47:54 rockpi-4a dockerd[3239]: time="2024-07-16T12:47:54.018178434+03:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.17.0.2:56040" dns-server="udp:8.8.8.8:53" error="read udp 172.17.0.2:56040->8.8.8.8:53: i/o timeout" question=";checkonline.home-assistant.io.\tIN\t A"
`
Debian 12, fresh install.I tryed change DNS, but it don't help. Any ideas?
