### ISSUE TITLE
Bug Report: Offline setup impossibility

### ISSUE THREAD

**Issue by Ikity** [home-assistant/supervised-installer#377]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux bananapim2berry 6.1.37-sunxi #1 SMP Sat Jul  1 11:16:27 UTC 2023 armv7l GNU/Linux

### What happened?

Successfully installed home assistant on this SBC everything work fine when connected to internet, but when trying to boot same configuration offline can't start supervisor. It seems it tries to pull image every even if it exist on machine 

> ghcr.io/esphome/esphome-hassio                   2024.8.0    5d32204c9dfc   13 days ago     1.06GB
> ghcr.io/home-assistant/armv7-hassio-supervisor   2024.08.0   538703750f12   4 weeks ago     334MB
> ghcr.io/home-assistant/armv7-hassio-supervisor   latest      538703750f12   4 weeks ago     334MB
> zigbee2mqtt/zigbee2mqtt-armhf                    1.39.1-1    be4b3785bcf3   4 weeks ago     138MB
> homeassistant/armhf-addon-samba                  12.3.2      75d981b4e47d   5 weeks ago     77.7MB
> ghcr.io/home-assistant/armv7-hassio-cli          2024.07.0   f442ce16eee5   5 weeks ago     44.9MB
> homeassistant/armhf-addon-mosquitto              6.4.1       7a100b56ab0c   3 months ago    195MB
> ghcr.io/hassio-addons/ssh/armv7                  18.0.0      19d25b83391d   3 months ago    270MB
> homeassistant/armhf-addon-rpc_shutdown           2.5         77ea59bf42bc   4 months ago    68.2MB
> ghcr.io/home-assistant/armv7-hassio-dns          2024.04.0   eeb1b8b94132   5 months ago    50.7MB
> ghcr.io/home-assistant/armv7-hassio-multicast    2024.03.0   b4f382c64d6e   5 months ago    35.2MB
> homeassistant/armhf-addon-configurator           5.8.0       877e1ca4a756   6 months ago    112MB
> ghcr.io/hassio-addons/motioneye/armhf            0.20.0      4043a26f34b3   8 months ago    251MB
> ghcr.io/hassio-addons/mqtt-io/armv7              0.4.0       cd2313ce1708   8 months ago    69.3MB
> ghcr.io/home-assistant/armv7-hassio-audio        2023.12.0   3ddd35faa4dd   8 months ago    57.3MB
> ghcr.io/home-assistant/armv7-hassio-observer     2023.06.0   68a99a8a7950   14 months ago   7.55MB

I tried to set ghcr.io to localhost bu to no avail stuck with same.

> Sep 04 01:10:51 bananapim2berry dockerd[1146]: time="2024-09-04T01:10:51.790296029+08:00" level=warning msg="Error getting v2 registry: Get \"https://ghcr.io/v2/\": dial tcp 127.0.0.1:443: connect: connection refused"
> Sep 04 01:10:51 bananapim2berry dockerd[1146]: time="2024-09-04T01:10:51.790654935+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://ghcr.io/v2/\": dial tcp 127.0.0.1:443: connect: connection refused"
> Sep 04 01:10:51 bananapim2berry dockerd[1146]: time="2024-09-04T01:10:51.793067193+08:00" level=warning msg="Error getting v2 registry: Get \"http://ghcr.io/v2/\": dial tcp 127.0.0.1:80: connect: connection refused"
> Sep 04 01:10:51 bananapim2berry dockerd[1146]: time="2024-09-04T01:10:51.793383558+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"http://ghcr.io/v2/\": dial tcp 127.0.0.1:80: connect: connection refused"
> Sep 04 01:10:51 bananapim2berry dockerd[1146]: time="2024-09-04T01:10:51.801907959+08:00" level=error msg="Handler for POST /v1.46/images/create returned error: Get \"http://ghcr.io/v2/\": dial tcp 127.0.0.1:80: connect: connection refused"
> Sep 04 01:10:51 bananapim2berry hassio_supervisor[1146]: 2024-09-03 22:10:51.807 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/qemuarm-homeassistant:2024.8.3: 500 Server Error for http+docker://localhost/v1.46/images/create?tag=2024.8.3&fromImage=ghcr.io%2Fhome-assistant%2Fqemuarm-homeassistant&platform=linux%2Farm%2Fv7>
> Sep 04 01:10:51 bananapim2berry hassio_supervisor[1146]: 2024-09-03 22:10:51.808 INFO (MainThread) [supervisor.homeassistant.core] No Home Assistant Docker image ghcr.io/home-assistant/qemuarm-homeassistant found.
> Sep 04 01:10:51 bananapim2berry hassio_supervisor[1146]: 2024-09-03 22:10:51.835 INFO (MainThread) [supervisor.homeassistant.core] Setting up Home Assistant landingpage
> Sep 04 01:10:51 bananapim2berry hassio_supervisor[1146]: 2024-09-03 22:10:51.836 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemuarm-homeassistant with tag landingpage

### Machine Type

qemuarm-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
Not able to recreate the issue but I am on x86_64. As long as the image is on device it doesn't seem to pull
