### ISSUE TITLE
Bug Report: the latest version of download not sync with main branch

### ISSUE THREAD

**Issue by saury** [home-assistant/supervised-installer#381]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux raspberrypi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

### What happened?

I saw this commit: https://github.com/home-assistant/supervised-installer/commit/a140122c6c408632c495f58e285e79097c345e09
but script among v1.8.0 is still old one. 
For Chinese user, they will always get ping error by running the installation of deb:
`PING checkonline.home-assistant.io (198.18.0.44) 56(84) bytes of data.`
For anyone who meet this error, you can folk -> add tag -> wait for the release package or use my directly as a workaround for currently.
https://github.com/saury/supervised-installer/releases/tag/1.9.0

### Machine Type

raspberrypi3-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
Check the latest release https://github.com/home-assistant/supervised-installer/releases/tag/2.0.0
