### ISSUE TITLE
Should I update this package on a running HA supervised instance?

### ISSUE THREAD

**Issue by nerthazrim** [home-assistant/supervised-installer#387]
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux hassio 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux

### What happened?

Maybe a stupid question. Sorry if it is.

Should I update the .deb package manually on a running HA supervised instance?
Download the .deb, apt install it?

### Machine Type

qemux86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment]
Yep you are correct just follow the README to make sure all dependencies are present and updated then apt install and you should be good to go just make sure you reboot the instance afterwards. I would however **strongly recommend you take a backup of Home Assistant beforehand** as a precaution as you would with any server maintenance in the case that anything does go wrong. But me myself, I haven't had any issues upgrading my systems
