### ISSUE TITLE
Provide an CLI mechanics like on HassOS for CLI

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/supervised-installer#54]

**Comment by andygrunwald** [comment]
HEy @pvizeli,
I see this issue has a `help-wanted` batch.
I am not 100% sure if I understand what is the idea behind this issue. Does it have something to do with https://github.com/home-assistant/hassos-cli ?

A few questions that come into my mind:
- What is the problem this issue should solve?
- Is there a link / repo / source code that is in use already (the title refers to HassOS)?
- How does the perfect end state should look like? (e.g. a small user story? As a user I want to do this or that by executing foo) ?

It would be good to have more context here. This can enable others to help. Thank you.

**Comment by andygrunwald** [comment]
Or does it have todo with this one? https://github.com/home-assistant/hassos-cli

**Comment by pvizeli** [comment]
It's a script they jump into cli container like on HassOS

**Comment by rct** [comment]
I have tried to manually install the `ha` CLI on the host, however I don't think the supervisor's API port is exposed to the host by default.  

If homeassistant is running, I can set `SUPERVISOR_ENDPOINT` to `http://hostname:8123/` and then I can do `ha` commands on the host. 

However that is of no use if homeassistant isn't running.

This is related to the problem in #1529 - I can't use the `ha` command in add-on if `supervisor` doesn't restart the add-on container.

**Comment by pvizeli** [comment]
Fix now
