### ISSUE TITLE
How to remove

### ISSUE THREAD

**Issue by bigverm23** [home-assistant/supervised-installer#90]
can you please let me know how to uninstall this script

**Comment by conrad760** [comment]
I was able to stop it with 
`systemctl disable hassio-apparmor.service hassio-supervisor.service
`
`systemctl stop hassio-apparmor.service hassio-supervisor.service
`

`docker stop $(docker ps -a -q)
`
`docker rm $(docker ps -a -q)`

careful you don't have any containers you want to save here^^^

**Comment by dereitz** [comment]
acsands13 posted some instructions to another issue below that might help others with removal:

https://github.com/home-assistant/supervisor/issues/1576#issuecomment-610156611
