### ISSUE TITLE
Hassio stop udev[182]: starting eudev-3.2.9

### ISSUE THREAD

**Issue by pure-graphene** [home-assistant/supervised-installer#91]
Hi,

The Hassio installation stops on [45.794270] udev[182]: starting eudev-3.2.9
Any tip on this?

Thanks,

**Comment by pvizeli** [comment]
`journalctl -fu hassio-supervisor`

Any more info about you system and OS?

**Comment by pure-graphene** [comment]
sorry, new at this.
trying to install on Raspberry Pi 3

**Comment by pure-graphene** [comment]
> sorry, new at this.
> trying to install version 64 bits on Raspberry Pi 3

![WhatsApp Image 2020-03-25 at 18 02 19](https://user-images.githubusercontent.com/62667156/77580953-bfe80f00-6ed4-11ea-9f16-0c0feeced886.jpeg)
