### ISSUE TITLE
Installation stuck on 'Preparing Home Assistant' using latest script

### ISSUE THREAD

**Issue by mwasowski** [home-assistant/supervised-installer#93]
Hi,

I am unable to install Home Assistant using the latest supervised script on Docker. I have a fresh Debian 10 VM I created in Proxmox, updated, installed only required packages for Docker and those for HA when attempting install. Only other piece of software I installed is Portainer - without issues.
I am using command from the GitHub page

`curl -sL https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh | bash -s`

The script itself finishes without errors but when I navigate to X.X.X.X:8123 I'm stuck on the 'Preparing Home Assistant' page. Yes, I've waited 20 minutes ;) Looking at browser developer tools, network tab I see 404 getting manifest.json that retries and fails over and over again. Digging a bit deeper I see that it loops on this method, failing mentioned above manifest.json fetch
```
function testAvailable() {
  fetch("./manifest.json").then(function(res) {
    if (res.ok) {
      location.reload();
    } else {
      scheduleTry();
    }
  }, scheduleTry);
}
```
Any ideas?

Thanks in advance,
Michal

**Comment by pvizeli** [comment]
https://github.com/home-assistant/supervised-installer/blob/master/README.md#troubleshooting

**Comment by mwasowski** [comment]
Why was this closed. If you need more info, just let me know, I admit I did miss the Troubleshooting section at the bottom.

First..I don't want a VM dedicated to Home Assistant, I want to run it on a VM that will run all my other 'bigger container.

Second, in the logs I see
```
mar 31 17:02:15 hassio-supervisor[2688]: 20-03-31 15:02:15 INFO (SyncWorker_0) [supervisor.docker.interface] Update image homeassistant/qemux86-64-homeassistant:landingpage to homeassistant/qemux86-64-homeassistant:0.107.7
mar 31 17:02:15 hassio-supervisor[2688]: 20-03-31 15:02:15 INFO (SyncWorker_0) [supervisor.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.107.7.
mar 31 17:02:37 dockerd[440]: time="2020-03-31T17:02:37.105768577+02:00" level=error msg="Download failed: write /var/lib/docker/tmp/GetImageBlob686552845: no space left on device"
mar 31 17:02:37 dockerd[440]: time="2020-03-31T17:02:37.121812592+02:00" level=info msg="Attempting next endpoint for pull after error: write /var/lib/docker/tmp/GetImageBlob686552845: no space left on device"
mar 31 17:02:37 hassio-supervisor[2688]: 20-03-31 15:02:37 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.107.7 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.107.7: No such image: homeassistant/qemux86-64-homeassistant:0.107.7").
mar 31 17:02:37 hassio-supervisor[2688]: 20-03-31 15:02:37 WARNING (MainThread) [supervisor.homeassistant] Error on install Home Assistant. Retry in 30sec
```

**Comment by mwasowski** [comment]
And just so we're clear with "no space left on device". There is plenty of space, over 10GB left..
