### ISSUE TITLE
hassio_supervisor dont't start homeassistant container at boot

### ISSUE THREAD

**Issue by blademckain** [home-assistant/supervised-installer#94]
this is the log of the hassio_supervisor container:

`
20-04-02 13:05:07 INFO (MainThread) [__main__] Initialize Supervisor setup
20-04-02 13:05:07 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 214
20-04-02 13:05:07 INFO (MainThread) [__main__] Setup Supervisor
20-04-02 13:05:07 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-04-02 13:05:07 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-04-02 13:05:07 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-04-02 13:05:07 WARNING (MainThread) [supervisor.dbus.nmi_dns] No DnsManager support on the host. Local DNS functions have been disabled.
20-04-02 13:05:07 INFO (MainThread) [supervisor.host.info] Update local host information
20-04-02 13:05:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-04-02 13:05:07 INFO (MainThread) [supervisor.host.services] Update service information
20-04-02 13:05:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-04-02 13:05:07 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-04-02 13:05:07 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-04-02 13:05:07 INFO (MainThread) [supervisor.host.apparmor] AppArmor is not enabled on host
20-04-02 13:05:07 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-audio with version 9
20-04-02 13:05:07 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-cli with version 24
20-04-02 13:05:07 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 3
20-04-02 13:05:07 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-04-02 13:05:07 INFO (SyncWorker_3) [supervisor.docker.interface] Restart homeassistant/amd64-hassio-dns
20-04-02 13:05:12 INFO (MainThread) [supervisor.dns] Updated /etc/resolv.conf
20-04-02 13:05:12 INFO (SyncWorker_4) [supervisor.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.107.7
20-04-02 13:05:12 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-04-02 13:05:12 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-04-02 13:05:12 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 65 new - 0 remove
20-04-02 13:05:12 INFO (MainThread) [supervisor.addons] Found 0 installed add-ons
20-04-02 13:05:12 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-04-02 13:05:12 INFO (MainThread) [supervisor.snapshots] Found 0 snapshot files
20-04-02 13:05:12 INFO (MainThread) [supervisor.discovery] Load 0 messages
20-04-02 13:05:12 INFO (MainThread) [supervisor.ingress] Load 0 ingress session
20-04-02 13:05:12 INFO (MainThread) [supervisor.secrets] Load Home Assistant secrets: 1
20-04-02 13:05:12 INFO (MainThread) [__main__] Run Supervisor
20-04-02 13:05:12 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-04-02 13:05:12 INFO (MainThread) [supervisor.addons] Phase 'initialize' start 0 add-ons
20-04-02 13:05:12 INFO (MainThread) [supervisor.core] Supervisor reboot detected
20-04-02 13:05:12 INFO (MainThread) [supervisor.tasks] All core tasks are scheduled
20-04-02 13:05:12 INFO (MainThread) [supervisor.hwmon] Started Supervisor hardware monitor
20-04-02 13:05:12 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-04-02 13:05:12 INFO (MainThread) [supervisor.host.info] Update local host information
20-04-02 13:05:12 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-04-02 13:05:12 INFO (MainThread) [supervisor.host.services] Update service information
20-04-02 13:05:12 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
`

but the container homeassistant/qemux86-64-homeassistant still Stopped

**Comment by pvizeli** [comment]
`ha core start`
