### ISSUE TITLE
Possible to reword some of the ‘Warning’ section of the readme?

### ISSUE THREAD

**Issue by carver7** [home-assistant/supervised-installer#99]
Some of ‘Warning’ section of the readme is a little difficult to understand.

> The Supervisor is also not caring for other software they run on your Host, and it can affect things bad on both sides. 

Is this what is meant by the sentence above? :
‘Conflicts can happen between Supervisor and other software run on your Host.’

> You also need to know that the Home Assistant OS runs with less overhead on your Proxmox or other Hypervisor as if you install first Debian and Ubuntu.

Is this what is meant by the sentence above? :
‘Note that Home Assistant OS runs with less overhead on your Proxmox or other Hypervisor if you install first Debian and Ubuntu.’

> In most cases, it's not the best choice to run the Supervisord on top of a Linux, if you not 100% sure what you do

Is this saying you don’t recommended installing Home Assistant Supervised?

> Customizations to your custom operating system may interfere with Home Assistant. For that reason, please be sure you have to knowledge to manage, configure and maintain the operating system of your choosing.

Are there any details regarding this that you can provide please, if one would like to be able to use the add-ons but not dedicate an entire computer to only home assistant?

**Comment by frenck** [comment]
> Is this what is meant by the sentence above? :
‘Conflicts can happen between Supervisor and other software run on your Host.’

Not only conflicts. They can also effect in other ways: Networking, memory, hardware handling...

> Is this what is meant by the sentence above? :
‘Note that Home Assistant OS runs with less overhead on your Proxmox or other Hypervisor if you install first Debian and Ubuntu.’

Home Assistant OS is lighter compared to installing a Supervised system on top of Debian or Ubuntu.

> Is this saying you don’t recommended installing Home Assistant Supervised?

We don't recommend it indeed.

> Are there any details regarding this that you can provide please, if one would like to be able to use the add-ons but not dedicate an entire computer to only home assistant?

Use VMs to isolate your virtual machines and it will allow you to use your computer for multiple things without dedicating it.
